### EDA

In [ ]:
# importing pandas library
import pandas as pd

In [ ]:
!pip install pandas

In [ ]:
#importing datasets
df=pd.read_csv("customer_shopping_behavior.csv")

In [ ]:
df

In [111]:
#show top rows
df.head(100)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.000000,California,XL,Olive,Winter,3.20,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.000000,South Carolina,M,White,Spring,3.90,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.000000,Montana,M,Black,Winter,3.10,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.000000,Illinois,L,Red,Fall,4.20,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.000000,Alabama,L,Yellow,Spring,3.60,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.000000,California,S,Beige,Summer,3.40,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.000000,Wisconsin,M,Brown,Summer,3.79,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.000000,Tennessee,M,Purple,Summer,4.00,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.000000,Florida,M,Red,Spring,4.30,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.000000,Kentucky,S,Yellow,Winter,2.80,Yes,Store Pickup,Yes,7.0,Cash,Monthly
10,4568,35,Other,Shoes,Footwear,276.343790,Phoenix,M,Blue,Autumn,3.55,No,Express,Yes,41.0,Credit Card,Monthly
11,947,46,Male,Coat,Outerwear,24.000000,Pennsylvania,XL,Blue,Spring,2.80,Yes,Next Day Air,Yes,4.0,PayPal,Quarterly
12,4776,64,Other,Laptop,Electronics,884.040000,Los Angeles,Not Applicable,Black,Spring,3.19,No,Express,No,0.0,Credit Card,Quarterly
13,3855,57,Female,T-shirt,Clothing,20.000000,Florida,M,Black,Spring,4.20,No,Free Shipping,No,4.0,Venmo,Annually
14,481,68,Male,Hoodie,Clothing,88.000000,Vermont,M,Gray,Summer,4.80,Yes,Standard,Yes,30.0,Debit Card,Bi-Weekly
15,3790,56,Female,Shirt,Clothing,75.000000,North Dakota,M,Magenta,Summer,3.80,No,Express,No,18.0,Bank Transfer,Every 3 Months
16,3617,42,Female,Hoodie,Clothing,23.000000,Wisconsin,L,Purple,Winter,3.30,No,Store Pickup,No,33.0,Debit Card,Fortnightly
17,2659,52,Female,Handbag,Accessories,47.000000,Ohio,XL,Indigo,Summer,3.20,No,Next Day Air,No,39.0,PayPal,Monthly
18,3725,30,Female,Gloves,Accessories,71.000000,Colorado,L,Green,Winter,3.10,No,Express,No,18.0,Bank Transfer,Annually
19,2134,21,Male,Hat,Accessories,34.000000,Maine,M,Olive,Summer,3.80,No,Standard,No,13.0,Bank Transfer,Annually
20,4256,70,Male,Phone,Electronics,734.477349,Los Angeles,Not Applicable,Green,Autumn,2.94,Yes,Standard,Yes,25.0,Cash,Weekly
21,833,58,Male,Jacket,Outerwear,80.000000,California,L,Blue,Fall,2.50,Yes,Express,Yes,28.0,Cash,Bi-Weekly
22,1106,33,Male,T-shirt,Clothing,83.000000,Massachusetts,S,Olive,Spring,3.00,No,Next Day Air,Yes,6.0,Venmo,Every 3 Months
23,3047,60,Female,Shoes,Footwear,49.000000,Pennsylvania,M,White,Spring,3.20,No,Store Pickup,No,25.0,Cash,Every 3 Months
24,4685,68,Other,Phone,Electronics,1032.090000,Phoenix,L,Black,Summer,2.94,No,Express,No,0.0,PayPal,Monthly
25,1612,41,Male,Pants,Clothing,26.000000,Arkansas,L,Yellow,Winter,4.50,No,Next Day Air,Yes,6.0,Debit Card,Monthly
26,4289,34,Female,Phone,Electronics,1282.440000,New York,S,Red,Autumn,2.94,No,Express,Yes,36.0,PayPal,Weekly
27,3552,66,Female,Gloves,Accessories,31.000000,Montana,L,Black,Spring,2.60,No,Store Pickup,No,20.0,Venmo,Weekly
28,2918,58,Female,Shirt,Clothing,45.000000,Colorado,XL,White,Winter,2.90,No,Store Pickup,No,50.0,Venmo,Annually
29,1192,34,Male,T-shirt,Clothing,70.000000,Indiana,L,Charcoal,Winter,4.10,No,Free Shipping,Yes,50.0,Venmo,Quarterly
30,1907,23,Male,Backpack,Accessories,30.000000,Vermont,M,Green,Spring,4.60,No,2-Day Shipping,No,24.0,PayPal,Fortnightly
31,1332,38,Male,Socks,Clothing,91.000000,Maryland,M,Lavender,Spring,3.20,No,Standard,Yes,8.0,PayPal,Bi-Weekly
32,316,66,Male,Jewelry,Accessories,24.000000,Wisconsin,XL,Orange,Spring,4.50,Yes,Express,Yes,24.0,Debit Card,Annually
33,347,49,Male,Jeans,Clothing,50.000000,New Mexico,L,Violet,Spring,4.70,Yes,Next Day Air,Yes,5.0,Cash,Weekly
34,3115,21,Female,Handbag,Accessories,56.000000,Arkansas,M,Olive,Spring,4.70,No,Store Pickup,No,45.0,Venmo,Bi-Weekly
35,5042,46,Other,Bag,Accessories,735.773625,Los Angeles,M,White,Summer,3.17,Yes,Express,No,31.0,PayPal,Monthly
36,1498,69,Male,Jacket,Outerwear,33.000000,Michigan,S,Magenta,Spring,3.80,No,2-Day Shipping,Yes,16.0,Debit Card,Every 3 Months
37,1606,70,Male,Belt,Accessories,46.000000,Connecticut,M,Lavender,Winter,3.40,No,Next Day Air,Yes,15.0,Credit Card,Bi-Weekly
38,4418,67,Female,Watch,Electronics,685.231471,Los Angeles,Not Applicable,Red,Autumn,3.10,No,Express,No,47.0,PayPal,Quarterly
39,4894,24,Other,Bag,Accessories,735.773625,Los Angeles,L,Red,Spring,3.17,No,Standard,No,4.0,PayPal,Quarterly
40,4576,65,Male,Headphones,Electronics,831.344565,New York,S,Black,Summer,3.08,No,Standard,Yes,47.0,Cash,Weekly
41,2486,43,Male,Blouse,Clothing,55.000000,Louisiana,M,Beige,Spring,4.60,No,2-Day Shipping,No,37.0,Bank Transfer,Annually
42,187,39,Male,Backpack,Accessories,56.000000,Minnesota,S,Lavender,Summer,2.90,Yes,Standard,Yes,31.0,Debit Card,Annually
43,275,59,Male,Jewelry,Accessories,32.000000,Maryland,M,Indigo,Spring,3.00,Yes,Express,Yes,28.0,Cash,Bi-Weekly
44,1402,23,Male,Sandals,Footwear,59.000000,Indiana,M,Blue,Fall,3.50,No,2-Day Shipping,Yes,1.0,PayPal,Weekly
45,1181,23,Male,Skirt,Clothing,23.000000,Oregon,S,Beige,Spring,4.90,No,Standard,Yes,34.0,Cash,Monthly
46,2130,40,Male,Skirt,Clothing,57.000000,Minnesota,L,Orange,Fall,2.80,No,Store Pickup,No,12.0,PayPal,Every 3 Months
47,995,53,Male,Shoes,Footwear,68.000000,New York,L,Violet,Fall,3.20,Yes,Express,Yes,20.0,Debit Card,Monthly
48,1230,34,Male,Jewelry,Accessories,52.000000,Kansas,XL,Maroon,Winter,3.60,No,Express,Yes,39.0,Bank Transfer,Annually
49,4319,47,Other,Watch,Electronics,685.231471,Houston,Not Applicable,Green,Summer,3.10,Yes,Express,Yes,28.0,PayPal,Monthly
50,4489,36,Female,Phone,Electronics,748.610000,Los Angeles,L,Red,Summer,2.94,No,Express,No,0.0,PayPal,Monthly
51,4708,33,Female,Bag,Accessories,735.773625,New York,Not Applicable,Green,Winter,4.00,Yes,Standard,Yes,31.0,Debit Card,Quarterly
52,4827,20,Female,Laptop,Electronics,805.502027,Houston,Not Applicable,Green,Summer,3.19,No,Express,No,17.0,Debit Card,Monthly
53,1348,44,Male,Sweater,Clothing,95.000000,Vermont,M,Cyan,Summer,3.90,No,2-Day Shipping,Yes,47.0,Bank Transfer,Monthly
54,4584,55,Female,Watch,Electronics,685.231471,New York,M,Black,Autumn,5.00,No,Express,Yes,0.0,Debit Card,Quarterly
55,3116,26,Female,Scarf,Accessories,53.000000,South Dakota,M,Charcoal,Fall,4.10,No,Free Shipping,No,9.0,Bank Transfer,Bi-Weekly
56,1168,60,Male,Socks,Clothing,83.000000,New Jersey,XL,Beige,Summer,3.60,No,Free Shipping,Yes,16.0,PayPal,Quarterly
57,3685,29,Female,Skirt,Clothing,86.000000,Pennsylvania,L,Charcoal,Spring,4.40,No,Free Shipping,No,47.0,Credit Card,Bi-Weekly
58,4111,49,Male,Phone,Electronics,734.477349,Houston,M,Black,Summer,2.94,No,Express,No,0.0,PayPal,Weekly
59,2850,56,Female,Coat,Outerwear,25.000000,New Hampshire,M,Gold,Spring,4.10,No,Express,No,27.0,PayPal,Bi-Weekly
60,1636,68,Male,Sunglasses,Accessories,24.000000,North Carolina,L,Violet,Summer,3.20,No,Standard,Yes,40.0,Cash,Annually
61,1489,23,Male,Hat,Accessories,44.000000,Hawaii,L,Pink,Winter,4.00,No,Standard,Yes,37.0,Credit Card,Weekly
62,3827,50,Female,Jacket,Outerwear,31.000000,Montana,M,Gray,Summer,4.00,No,Express,No,25.0,Bank Transfer,Annually
63,2417,59,Male,Sandals,Footwear,83.000000,Nebraska,S,Black,Summer,4.00,No,Next Day Air,No,26.0,Credit Card,Every 3 Months
64,2832,34,Female,Hoodie,Clothing,53.000000,Virginia,L,Pink,Winter,5.00,No,Express,No,4.0,Credit Card,Weekly
65,4607,47,Other,Shirt,Clothing,557.240000,Los Angeles,L,White,Autumn,3.43,No,Express,Yes,27.0,PayPal,Weekly
66,2367,30,Male,Shoes,Footwear,66.000000,New Mexico,L,Brown,Winter,3.60,No,Express,No,32.0,Credit Card,Fortnightly
67,4851,42,Female,Watch,Electronics,685.231471,Chicago,L,Blue,Autumn,3.10,No,Standard,Yes,0.0,Cash,Weekly
68,508,65,Male,Shorts,Clothing,20.000000,Maine,M,Magenta,Spring,5.00,Yes,Store Pickup,Yes,33.0,Debit Card,Fortnightly
69,4845,19,Female,Shirt,Clothing,692.110000,New York,M,Red,Summer,3.43,No,Express,Yes,41.0,Debit Card,Weekly
70,2098,33,Male,Sneakers,Footwear,43.000000,Iowa,S,Cyan,Winter,3.90,No,Next Day Air,No,5.0,Credit Card,Weekly
71,1080,18,Male,Coat,Outerwear,33.000000,Oklahoma,S,Blue,Summer,4.40,No,Free Shipping,Yes,48.0,Bank Transfer,Monthly
72,4558,41,Other,Bag,Accessories,208.020000,Los Angeles,M,White,Autumn,3.17,No,Standard,Yes,0.0,PayPal,Monthly
73,4492,59,Female,Laptop,Electronics,805.502027,Phoenix,M,Green,Spring,1.00,Yes,Standard,Yes,38.0,Debit Card,Weekly
74,4292,27,Other,Laptop,Electronics,805.502027,Houston,Not Applicable,Blue,Summer,3.19,Yes,Express,Yes,0.0,Credit Card,Weekly
75,3036,69,Female,Handbag,Accessories,64.000000,Kentucky,M,Gold,Spring,4.50,No,Free Shipping,No,18.0,Cash,Bi-Weekly
76,3554,62,Female,Shoes,Footwear,99.000000,Minnesota,M,Charcoal,Spring,4.90,No,Free Shipping,No,32.0,Bank Transfer,Weekly
77,2077,59,Male,Gloves,Accessories,23.000000,Florida,S,Indigo,Fall,4.60,No,Free Shipping,No,22.0,Debit Card,Bi-Weekly
78,3088,62,Female,Shirt,Clothing,84.000000,North Carolina,M,Charcoal,Spring,3.10,No,Free Shipping,No,29.0,Bank Transfer,Monthly
79,3739,34,Female,Shorts,Clothing,45.000000,Delaware,M,Brown,Spring,2.70,No,Free Shipping,No,48.0,Cash,Fortnightly
80,3309,55,Female,Jeans,Clothing,70.000000,Utah,M,Pink,Fall,2.60,No,Express,No,29.0,Cash,Monthly
81,2922,20,Female,Handbag,Accessories,24.000000,Wisconsin,M,Cyan,Fall,4.60,No,Standard,No,11.0,Cash,Fortnightly
82,4156,51,Other,Shirt,Clothing,1398.900000,Chicago,XL,Red,Summer,2.00,Yes,Express,No,7.0,PayPal,Monthly
83,4869,26,Female,Headphones,Electronics,500.300000,Phoenix,M,Red,Winter,3.00,No,Express,No,0.0,PayPal,Monthly
84,660,62,Male,Shorts,Clothing,52.000000,Virginia,S,Gold,Spring,3.60,Yes,2-Day Shipping,Yes,8.0,Cash,Weekly
85,3632,48,Female,Hat,Accessories,50.000000,New Jersey,M,Peach,Fall,2.90,No,Store Pickup,No,26.0,Credit Card,Monthly
86,3217,39,Female,Hoodie,Clothing,85.000000,Illinois,S,Olive,Winter,3.40,No,Next Day Air,No,18.0,Cash,Weekly
87,3696,38,Female,Skirt,Clothing,33.000000,Florida,M,White,Fall,4.60,No,Standard,No,18.0,Bank Transfer,Fortnightly
88,146,24,Male,Jewelry,Accessories,95.000000,Missouri,M,Teal,Fall,4.50,Yes,Standard,Yes,44.0,Debit Card,Quarterly
89,693,35,Male,Sunglasses,Accessories,95.000000,North Dakota,M,Cyan,Spring,4.00,Yes,2-Day Shipping,Yes,40.0,Debit Card,Every 3 Months
90,1837,66,Male,Pants,Clothing,52.000000,South Carolina,M,Teal,Fall,4.20,No,2-Day Shipping,No,35.0,Credit Card,Monthly
91,598,70,Male,Jewelry,Accessories,69.000000,Alaska,L,Gold,Summer,3.40,Yes,Standard,Yes,19.0,Bank Transfer,Fortnightly
92,165,59,Male,Handbag,Accessories,65.000000,Delaware,S,Purple,Spring,2.60,Yes,Free Shipping,Yes,5.0,Credit Card,Fortnightly
93,1186,47,Male,Jeans,Clothing,64.000000,Maine,M,Magenta,Spring,3.90,No,Standard,Yes,29.0,Credit Card,Monthly
94,3328,47,Female,Shorts,Clothing,64.000000,Connecticut,M,Black,Spring,4.10,No,Express,No,2.0,Debit Card,Quarterly
95,4404,67,Male,Watch,Electronics,498.030000,New York,XL,Blue,Winter,3.10,Yes,Standard,Yes,20.0,Debit Card,Monthly
96,4153,67,Other,Shoes,Footwear,276.343790,Los Angeles,M,Red,Spring,3.55,No,Express,No,31.0,Credit Card,Monthly
97,4587,52,Male,Laptop,Electronics,1392.020000,Phoenix,Not Applicable,White,Winter,2.00,Yes,Standard,Yes,0.0,Cash,Quarterly
98,4057,41,Female,Shoes,Footwear,276.343790,Los Angeles,Not Applicable,Black,Winter,3.55,No,Standard,Yes,10.0,Credit Card,Quarterly
99,3889,45,Female,Sneakers,Footwear,69.000000,Virginia,M,Violet,Spring,3.40,No,Standard,No,14.0,Venmo,Bi-Weekly

In [112]:
df.shape

(5000, 17)

In [ ]:
df.tail(20)

In [ ]:
len(df)

In [ ]:
df.describe

In [ ]:
df.describe()

In [ ]:
df.describe(include="all")

In [ ]:
df.null()

In [ ]:
df.isnull()

### Data Cleaning

In [ ]:
df.head()

In [ ]:
df[['Category','Item Purchased']]

In [ ]:
df['Item Purchased'].unique()

In [ ]:
df.groupby('Category')['Item Purchased'].unique()

In [ ]:
df.groupby('Category')['Item Purchased'].unique()

In [ ]:
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [104]:
correct_mapping={
    
    # Accessories
    "Sunglasses": "Accessories", "Gloves": "Accessories","Jewelry": "Accessories",
    "Hat": "Accessories","Handbag": "Accessories","Backpack": "Accessories","Belt": "Accessories",
    "Bag": "Accessories","Scarf": "Accessories",

    # Clothing
    "T-shirt": "Clothing","Shirt": "Clothing","Shorts": "Clothing","Hoodie": "Clothing","Pants": "Clothing",
    "Socks": "Clothing","Jeans": "Clothing","Blouse": "Clothing",
    "Skirt": "Clothing","Sweater": "Clothing","Dress": "Clothing",

    # Electronics
    "Laptop": "Electronics", "Phone": "Electronics",
    "Watch": "Electronics","Headphones": "Electronics",

    # Footwear
    "Shoes": "Footwear", "Sandals": "Footwear","Sneakers": "Footwear","Boots": "Footwear",

    # Outerwear
    "Coat": "Outerwear","Jacket": "Outerwear"
}

In [103]:
df.groupby('category')['item_purchased'].unique()

category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: item_purchased, dtype: object

In [105]:
df['category']=df['item_purchased'].map(correct_mapping)

In [106]:
df.groupby('category')['item_purchased'].unique()

category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: item_purchased, dtype: object

In [10]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

# Treating The Null Value

In [108]:
df['size'].unique()

<StringArray>
['XL', 'M', 'L', 'S', 'Not Applicable']
Length: 5, dtype: str

In [21]:
df.head(200)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.00,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.00,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.00,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.00,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.00,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.00,California,S,Beige,Summer,3.4,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.00,Wisconsin,M,Brown,Summer,NaN,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.00,Tennessee,M,Purple,Summer,4.0,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.00,Florida,M,Red,Spring,4.3,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.00,Kentucky,S,Yellow,Winter,2.8,Yes,Store Pickup,Yes,7.0,Cash,Monthly
10,4568,35,Other,Shoes,Clothing,NaN,Phoenix,M,Blue,Autumn,NaN,No,Express,Yes,41.0,Credit Card,Monthly
11,947,46,Male,Coat,Outerwear,24.00,Pennsylvania,XL,Blue,Spring,2.8,Yes,Next Day Air,Yes,4.0,PayPal,Quarterly
12,4776,64,Other,Laptop,Electronics,884.04,Los Angeles,NaN,Black,Spring,NaN,No,Express,No,NaN,Credit Card,Quarterly
13,3855,57,Female,T-shirt,Clothing,20.00,Florida,M,Black,Spring,4.2,No,Free Shipping,No,4.0,Venmo,Annually
14,481,68,Male,Hoodie,Clothing,88.00,Vermont,M,Gray,Summer,4.8,Yes,Standard,Yes,30.0,Debit Card,Bi-Weekly
15,3790,56,Female,Shirt,Clothing,75.00,North Dakota,M,Magenta,Summer,3.8,No,Express,No,18.0,Bank Transfer,Every 3 Months
16,3617,42,Female,Hoodie,Clothing,23.00,Wisconsin,L,Purple,Winter,3.3,No,Store Pickup,No,33.0,Debit Card,Fortnightly
17,2659,52,Female,Handbag,Accessories,47.00,Ohio,XL,Indigo,Summer,3.2,No,Next Day Air,No,39.0,PayPal,Monthly
18,3725,30,Female,Gloves,Accessories,71.00,Colorado,L,Green,Winter,3.1,No,Express,No,18.0,Bank Transfer,Annually
19,2134,21,Male,Hat,Accessories,34.00,Maine,M,Olive,Summer,3.8,No,Standard,No,13.0,Bank Transfer,Annually
20,4256,70,Male,Phone,Electronics,NaN,Los Angeles,NaN,Green,Autumn,NaN,Yes,Standard,Yes,25.0,Cash,Weekly
21,833,58,Male,Jacket,Outerwear,80.00,California,L,Blue,Fall,2.5,Yes,Express,Yes,28.0,Cash,Bi-Weekly
22,1106,33,Male,T-shirt,Clothing,83.00,Massachusetts,S,Olive,Spring,3.0,No,Next Day Air,Yes,6.0,Venmo,Every 3 Months
23,3047,60,Female,Shoes,Footwear,49.00,Pennsylvania,M,White,Spring,3.2,No,Store Pickup,No,25.0,Cash,Every 3 Months
24,4685,68,Other,Phone,Clothing,1032.09,Phoenix,L,Black,Summer,NaN,No,Express,No,NaN,PayPal,Monthly
25,1612,41,Male,Pants,Clothing,26.00,Arkansas,L,Yellow,Winter,4.5,No,Next Day Air,Yes,6.0,Debit Card,Monthly
26,4289,34,Female,Phone,Accessories,1282.44,New York,S,Red,Autumn,NaN,No,Express,Yes,36.0,PayPal,Weekly
27,3552,66,Female,Gloves,Accessories,31.00,Montana,L,Black,Spring,2.6,No,Store Pickup,No,20.0,Venmo,Weekly
28,2918,58,Female,Shirt,Clothing,45.00,Colorado,XL,White,Winter,2.9,No,Store Pickup,No,50.0,Venmo,Annually
29,1192,34,Male,T-shirt,Clothing,70.00,Indiana,L,Charcoal,Winter,4.1,No,Free Shipping,Yes,50.0,Venmo,Quarterly
30,1907,23,Male,Backpack,Accessories,30.00,Vermont,M,Green,Spring,4.6,No,2-Day Shipping,No,24.0,PayPal,Fortnightly
31,1332,38,Male,Socks,Clothing,91.00,Maryland,M,Lavender,Spring,3.2,No,Standard,Yes,8.0,PayPal,Bi-Weekly
32,316,66,Male,Jewelry,Accessories,24.00,Wisconsin,XL,Orange,Spring,4.5,Yes,Express,Yes,24.0,Debit Card,Annually
33,347,49,Male,Jeans,Clothing,50.00,New Mexico,L,Violet,Spring,4.7,Yes,Next Day Air,Yes,5.0,Cash,Weekly
34,3115,21,Female,Handbag,Accessories,56.00,Arkansas,M,Olive,Spring,4.7,No,Store Pickup,No,45.0,Venmo,Bi-Weekly
35,5042,46,Other,Bag,Clothing,NaN,Los Angeles,M,White,Summer,NaN,Yes,Express,No,31.0,PayPal,Monthly
36,1498,69,Male,Jacket,Outerwear,33.00,Michigan,S,Magenta,Spring,3.8,No,2-Day Shipping,Yes,16.0,Debit Card,Every 3 Months
37,1606,70,Male,Belt,Accessories,46.00,Connecticut,M,Lavender,Winter,3.4,No,Next Day Air,Yes,15.0,Credit Card,Bi-Weekly
38,4418,67,Female,Watch,Electronics,NaN,Los Angeles,NaN,Red,Autumn,NaN,No,Express,No,47.0,PayPal,Quarterly
39,4894,24,Other,Bag,Accessories,NaN,Los Angeles,L,Red,Spring,NaN,No,Standard,No,4.0,PayPal,Quarterly
40,4576,65,Male,Headphones,Accessories,NaN,New York,S,Black,Summer,NaN,No,Standard,Yes,47.0,Cash,Weekly
41,2486,43,Male,Blouse,Clothing,55.00,Louisiana,M,Beige,Spring,4.6,No,2-Day Shipping,No,37.0,Bank Transfer,Annually
42,187,39,Male,Backpack,Accessories,56.00,Minnesota,S,Lavender,Summer,2.9,Yes,Standard,Yes,31.0,Debit Card,Annually
43,275,59,Male,Jewelry,Accessories,32.00,Maryland,M,Indigo,Spring,3.0,Yes,Express,Yes,28.0,Cash,Bi-Weekly
44,1402,23,Male,Sandals,Footwear,59.00,Indiana,M,Blue,Fall,3.5,No,2-Day Shipping,Yes,1.0,PayPal,Weekly
45,1181,23,Male,Skirt,Clothing,23.00,Oregon,S,Beige,Spring,4.9,No,Standard,Yes,34.0,Cash,Monthly
46,2130,40,Male,Skirt,Clothing,57.00,Minnesota,L,Orange,Fall,2.8,No,Store Pickup,No,12.0,PayPal,Every 3 Months
47,995,53,Male,Shoes,Footwear,68.00,New York,L,Violet,Fall,3.2,Yes,Express,Yes,20.0,Debit Card,Monthly
48,1230,34,Male,Jewelry,Accessories,52.00,Kansas,XL,Maroon,Winter,3.6,No,Express,Yes,39.0,Bank Transfer,Annually
49,4319,47,Other,Watch,Electronics,NaN,Houston,NaN,Green,Summer,NaN,Yes,Express,Yes,28.0,PayPal,Monthly
50,4489,36,Female,Phone,Accessories,748.61,Los Angeles,L,Red,Summer,NaN,No,Express,No,0.0,PayPal,Monthly
51,4708,33,Female,Bag,Electronics,NaN,New York,NaN,Green,Winter,4.0,Yes,Standard,Yes,31.0,Debit Card,Quarterly
52,4827,20,Female,Laptop,Electronics,NaN,Houston,NaN,Green,Summer,NaN,No,Express,No,17.0,Debit Card,Monthly
53,1348,44,Male,Sweater,Clothing,95.00,Vermont,M,Cyan,Summer,3.9,No,2-Day Shipping,Yes,47.0,Bank Transfer,Monthly
54,4584,55,Female,Watch,Clothing,NaN,New York,M,Black,Autumn,5.0,No,Express,Yes,NaN,Debit Card,Quarterly
55,3116,26,Female,Scarf,Accessories,53.00,South Dakota,M,Charcoal,Fall,4.1,No,Free Shipping,No,9.0,Bank Transfer,Bi-Weekly
56,1168,60,Male,Socks,Clothing,83.00,New Jersey,XL,Beige,Summer,3.6,No,Free Shipping,Yes,16.0,PayPal,Quarterly
57,3685,29,Female,Skirt,Clothing,86.00,Pennsylvania,L,Charcoal,Spring,4.4,No,Free Shipping,No,47.0,Credit Card,Bi-Weekly
58,4111,49,Male,Phone,Clothing,NaN,Houston,M,Black,Summer,NaN,No,Express,No,NaN,PayPal,Weekly
59,2850,56,Female,Coat,Outerwear,25.00,New Hampshire,M,Gold,Spring,4.1,No,Express,No,27.0,PayPal,Bi-Weekly
60,1636,68,Male,Sunglasses,Accessories,24.00,North Carolina,L,Violet,Summer,3.2,No,Standard,Yes,40.0,Cash,Annually
61,1489,23,Male,Hat,Accessories,44.00,Hawaii,L,Pink,Winter,4.0,No,Standard,Yes,37.0,Credit Card,Weekly
62,3827,50,Female,Jacket,Outerwear,31.00,Montana,M,Gray,Summer,4.0,No,Express,No,25.0,Bank Transfer,Annually
63,2417,59,Male,Sandals,Footwear,83.00,Nebraska,S,Black,Summer,4.0,No,Next Day Air,No,26.0,Credit Card,Every 3 Months
64,2832,34,Female,Hoodie,Clothing,53.00,Virginia,L,Pink,Winter,5.0,No,Express,No,4.0,Credit Card,Weekly
65,4607,47,Other,Shirt,Clothing,557.24,Los Angeles,L,White,Autumn,NaN,No,Express,Yes,27.0,PayPal,Weekly
66,2367,30,Male,Shoes,Footwear,66.00,New Mexico,L,Brown,Winter,3.6,No,Express,No,32.0,Credit Card,Fortnightly
67,4851,42,Female,Watch,Accessories,NaN,Chicago,L,Blue,Autumn,NaN,No,Standard,Yes,NaN,Cash,Weekly
68,508,65,Male,Shorts,Clothing,20.00,Maine,M,Magenta,Spring,5.0,Yes,Store Pickup,Yes,33.0,Debit Card,Fortnightly
69,4845,19,Female,Shirt,Accessories,692.11,New York,M,Red,Summer,NaN,No,Express,Yes,41.0,Debit Card,Weekly
70,2098,33,Male,Sneakers,Footwear,43.00,Iowa,S,Cyan,Winter,3.9,No,Next Day Air,No,5.0,Credit Card,Weekly
71,1080,18,Male,Coat,Outerwear,33.00,Oklahoma,S,Blue,Summer,4.4,No,Free Shipping,Yes,48.0,Bank Transfer,Monthly
72,4558,41,Other,Bag,Accessories,208.02,Los Angeles,M,White,Autumn,NaN,No,Standard,Yes,NaN,PayPal,Monthly
73,4492,59,Female,Laptop,Clothing,NaN,Phoenix,M,Green,Spring,1.0,Yes,Standard,Yes,38.0,Debit Card,Weekly
74,4292,27,Other,Laptop,Electronics,NaN,Houston,NaN,Blue,Summer,NaN,Yes,Express,Yes,NaN,Credit Card,Weekly
75,3036,69,Female,Handbag,Accessories,64.00,Kentucky,M,Gold,Spring,4.5,No,Free Shipping,No,18.0,Cash,Bi-Weekly
76,3554,62,Female,Shoes,Footwear,99.00,Minnesota,M,Charcoal,Spring,4.9,No,Free Shipping,No,32.0,Bank Transfer,Weekly
77,2077,59,Male,Gloves,Accessories,23.00,Florida,S,Indigo,Fall,4.6,No,Free Shipping,No,22.0,Debit Card,Bi-Weekly
78,3088,62,Female,Shirt,Clothing,84.00,North Carolina,M,Charcoal,Spring,3.1,No,Free Shipping,No,29.0,Bank Transfer,Monthly
79,3739,34,Female,Shorts,Clothing,45.00,Delaware,M,Brown,Spring,2.7,No,Free Shipping,No,48.0,Cash,Fortnightly
80,3309,55,Female,Jeans,Clothing,70.00,Utah,M,Pink,Fall,2.6,No,Express,No,29.0,Cash,Monthly
81,2922,20,Female,Handbag,Accessories,24.00,Wisconsin,M,Cyan,Fall,4.6,No,Standard,No,11.0,Cash,Fortnightly
82,4156,51,Other,Shirt,Clothing,1398.90,Chicago,XL,Red,Summer,2.0,Yes,Express,No,7.0,PayPal,Monthly
83,4869,26,Female,Headphones,Accessories,500.30,Phoenix,M,Red,Winter,3.0,No,Express,No,NaN,PayPal,Monthly
84,660,62,Male,Shorts,Clothing,52.00,Virginia,S,Gold,Spring,3.6,Yes,2-Day Shipping,Yes,8.0,Cash,Weekly
85,3632,48,Female,Hat,Accessories,50.00,New Jersey,M,Peach,Fall,2.9,No,Store Pickup,No,26.0,Credit Card,Monthly
86,3217,39,Female,Hoodie,Clothing,85.00,Illinois,S,Olive,Winter,3.4,No,Next Day Air,No,18.0,Cash,Weekly
87,3696,38,Female,Skirt,Clothing,33.00,Florida,M,White,Fall,4.6,No,Standard,No,18.0,Bank Transfer,Fortnightly
88,146,24,Male,Jewelry,Accessories,95.00,Missouri,M,Teal,Fall,4.5,Yes,Standard,Yes,44.0,Debit Card,Quarterly
89,693,35,Male,Sunglasses,Accessories,95.00,North Dakota,M,Cyan,Spring,4.0,Yes,2-Day Shipping,Yes,40.0,Debit Card,Every 3 Months
90,1837,66,Male,Pants,Clothing,52.00,South Carolina,M,Teal,Fall,4.2,No,2-Day Shipping,No,35.0,Credit Card,Monthly
91,598,70,Male,Jewelry,Accessories,69.00,Alaska,L,Gold,Summer,3.4,Yes,Standard,Yes,19.0,Bank Transfer,Fortnightly
92,165,59,Male,Handbag,Accessories,65.00,Delaware,S,Purple,Spring,2.6,Yes,Free Shipping,Yes,5.0,Credit Card,Fortnightly
93,1186,47,Male,Jeans,Clothing,64.00,Maine,M,Magenta,Spring,3.9,No,Standard,Yes,29.0,Credit Card,Monthly
94,3328,47,Female,Shorts,Clothing,64.00,Connecticut,M,Black,Spring,4.1,No,Express,No,2.0,Debit Card,Quarterly
95,4404,67,Male,Watch,Clothing,498.03,New York,XL,Blue,Winter,NaN,Yes,Standard,Yes,20.0,Debit Card,Monthly
96,4153,67,Other,Shoes,Accessories,NaN,Los Angeles,M,Red,Spring,NaN,No,Express,No,31.0,Credit Card,Monthly
97,4587,52,Male,Laptop,Electronics,1392.02,Phoenix,NaN,White,Winter,2.0,Yes,Standard,Yes,NaN,Cash,Quarterly
98,4057,41,Female,Shoes,Electronics,NaN,Los Angeles,NaN,Black,Winter,NaN,No,Standard,Yes,10.0,Credit Card,Quarterly
99,3889,45,Female,Sneakers,Footwear,69.00,Virginia,M,Violet,Spring,3.4,No,Standard,No,14.0,Venmo,Bi-Weekly
100,106,69,Male,Backpack,Accessories,96.00,New York,M,Charcoal,Fall,3.6,Yes,Next Day Air,Yes,4.0,Bank Transfer,Annually
101,4176,23,Male,Shoes,Clothing,390.25,Chicago,XL,Black,Autumn,NaN,No,Standard,No,NaN,Credit Card,Weekly
102,63,30,Male,Sneakers,Footwear,21.00,Mississippi,S,Magenta,Spring,3.8,Yes,Free Shipping,Yes,31.0,Credit Card,Fortnightly
103,3455,55,Female,Handbag,Accessories,71.00,Louisiana,S,Lavender,Fall,4.6,No,Store Pickup,No,15.0,PayPal,Bi-Weekly
104,2500,52,Male,Hoodie,Clothing,73.00,Louisiana,L,Pink,Summer,3.1,No,Next Day Air,No,2.0,Cash,Quarterly
105,2136,34,Male,Sunglasses,Accessories,94.00,California,S,Yellow,Winter,4.6,No,Next Day Air,No,1.0,Debit Card,Every 3 Months
106,3584,52,Female,Blouse,Clothing,77.00,Arizona,L,Brown,Summer,2.7,No,Store Pickup,No,44.0,Credit Card,Every 3 Months
107,4118,18,Other,Shirt,Accessories,NaN,Phoenix,S,Black,Summer,3.0,Yes,Standard,No,NaN,Debit Card,Quarterly
108,2547,63,Male,Boots,Footwear,21.00,Texas,L,Gray,Summer,3.0,No,Express,No,4.0,Credit Card,Quarterly
109,4972,46,Other,Bag,Accessories,34.65,New York,M,White,Autumn,4.0,No,Express,Yes,3.0,Debit Card,Monthly
110,3365,50,Female,Scarf,Accessories,33.00,Oregon,M,Peach,Fall,3.2,No,Standard,No,7.0,Credit Card,Monthly
111,1637,58,Male,Boots,Footwear,22.00,North Dakota,L,Green,Fall,4.0,No,Free Shipping,Yes,49.0,Cash,Fortnightly
112,2000,39,Male,Socks,Clothing,89.00,Tennessee,L,Indigo,Winter,4.6,No,2-Day Shipping,No,26.0,Debit Card,Monthly
113,2603,65,Male,Coat,Outerwear,44.00,South Carolina,M,Black,Fall,2.9,No,Free Shipping,No,1.0,Venmo,Quarterly
114,2700,25,Female,Boots,Footwear,96.00,Utah,M,Violet,Fall,3.6,No,2-Day Shipping,No,49.0,Debit Card,Annually
115,4189,38,Male,Shoes,Accessories,1312.35,Los Angeles,M,Black,Autumn,4.0,Yes,Standard,Yes,NaN,Cash,Weekly
116,3371,30,Female,Belt,Accessories,31.00,Illinois,M,Charcoal,Summer,2.8,No,Store Pickup,No,46.0,Cash,Fortnightly
117,3599,23,Female,Hoodie,Clothing,76.00,Connecticut,XL,Purple,Spring,4.6,No,Store Pickup,No,19.0,Bank Transfer,Bi-Weekly
118,4072,63,Male,Shoes,Clothing,NaN,Los Angeles,S,Red,Autumn,1.0,No,Standard,Yes,NaN,Credit Card,Quarterly
119,1432,39,Male,Pants,Clothing,88.00,South Dakota,M,Cyan,Fall,2.9,No,Express,Yes,29.0,Venmo,Quarterly
120,2381,41,Male,Scarf,Accessories,66.00,Pennsylvania,M,Black,Fall,2.5,No,Next Day Air,No,36.0,PayPal,Fortnightly
121,2120,58,Male,Jewelry,Accessories,57.00,Nebraska,M,Indigo,Spring,3.5,No,Store Pickup,No,36.0,Venmo,Bi-Weekly
122,3502,53,Female,Shoes,Footwear,87.00,Nebraska,M,Silver,Fall,4.8,No,Standard,No,43.0,Bank Transfer,Weekly
123,3551,63,Female,Shoes,Footwear,74.00,West Virginia,S,Orange,Winter,4.8,No,Standard,No,32.0,Cash,Weekly
124,712,64,Male,Boots,Footwear,60.00,New Hampshire,M,Maroon,Spring,3.5,Yes,2-Day Shipping,Yes,13.0,Bank Transfer,Bi-Weekly
125,1337,23,Male,Sneakers,Footwear,85.00,Oregon,M,Charcoal,Spring,4.8,No,Store Pickup,Yes,44.0,Debit Card,Fortnightly
126,1047,40,Male,Sneakers,Footwear,22.00,Illinois,M,Magenta,Winter,4.2,Yes,Standard,Yes,12.0,Venmo,Annually
127,2225,18,Male,Gloves,Accessories,25.00,Nebraska,L,Charcoal,Winter,4.3,No,Standard,No,38.0,Cash,Quarterly
128,3525,69,Female,Pants,Clothing,74.00,Michigan,L,Silver,Summer,2.9,No,Free Shipping,No,30.0,Credit Card,Monthly
129,4530,20,Male,Watch,Electronics,532.49,New York,NaN,Black,Autumn,NaN,Yes,Standard,Yes,NaN,Debit Card,Monthly
130,3199,61,Female,Gloves,Accessories,94.00,Pennsylvania,L,Peach,Winter,2.8,No,Free Shipping,No,39.0,Debit Card,Weekly
131,70,48,Male,Belt,Accessories,70.00,Tennessee,S,Cyan,Summer,4.4,Yes,Express,Yes,5.0,Cash,Weekly
132,2721,55,Female,Scarf,Accessories,52.00,Maryland,M,Peach,Spring,2.8,No,Store Pickup,No,45.0,Bank Transfer,Quarterly
133,436,51,Male,Coat,Outerwear,28.00,Montana,XL,Olive,Winter,3.6,Yes,Next Day Air,Yes,42.0,Bank Transfer,Monthly
134,387,64,Male,Jewelry,Accessories,39.00,Louisiana,L,Brown,Spring,3.4,Yes,Express,Yes,40.0,PayPal,Quarterly
135,3867,58,Female,Hat,Accessories,32.00,Alaska,M,Beige,Winter,3.3,No,2-Day Shipping,No,33.0,Credit Card,Fortnightly
136,3358,41,Female,Hoodie,Clothing,67.00,Arkansas,M,Pink,Winter,3.5,No,Free Shipping,No,37.0,Credit Card,Monthly
137,608,47,Male,Hoodie,Clothing,23.00,Indiana,L,Purple,Fall,2.8,Yes,Next Day Air,Yes,44.0,Cash,Monthly
138,115,70,Male,Coat,Outerwear,95.00,Massachusetts,S,Blue,Summer,3.7,Yes,Store Pickup,Yes,9.0,Cash,Weekly
139,4712,60,Male,Laptop,Clothing,95.15,Chicago,S,Red,Summer,NaN,No,Standard,No,16.0,Cash,Monthly
140,5058,63,Other,Shirt,Electronics,1342.62,Los Angeles,NaN,Blue,Spring,4.0,Yes,Standard,Yes,NaN,PayPal,Quarterly
141,2568,19,Male,Sunglasses,Accessories,25.00,Michigan,XL,Gold,Spring,4.3,No,Store Pickup,No,24.0,Cash,Fortnightly
142,4381,53,Female,Watch,Clothing,NaN,Chicago,M,Blue,Summer,3.0,No,Express,Yes,NaN,PayPal,Monthly
143,4192,46,Other,Watch,Electronics,105.21,Houston,NaN,Green,Winter,NaN,Yes,Standard,Yes,NaN,PayPal,Monthly
144,235,20,Male,Gloves,Accessories,39.00,South Dakota,S,Silver,Summer,3.7,Yes,Next Day Air,Yes,24.0,Credit Card,Weekly
145,3699,25,Female,Skirt,Clothing,54.00,California,XL,Maroon,Spring,4.0,No,2-Day Shipping,No,4.0,Venmo,Annually
146,3215,53,Female,Skirt,Clothing,78.00,Washington,M,Yellow,Spring,3.1,No,Free Shipping,No,6.0,Debit Card,Annually
147,1876,63,Male,Boots,Footwear,71.00,Tennessee,M,Brown,Winter,3.9,No,Next Day Air,No,6.0,Credit Card,Quarterly
148,1625,38,Male,Sweater,Clothing,32.00,Florida,M,White,Winter,3.6,No,Free Shipping,Yes,40.0,PayPal,Every 3 Months
149,1396,47,Male,Scarf,Accessories,32.00,West Virginia,L,Turquoise,Spring,2.8,No,Next Day Air,Yes,40.0,PayPal,Bi-Weekly
150,9,26,Male,Coat,Outerwear,97.00,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8.0,Venmo,Annually
151,2168,30,Male,Skirt,Clothing,48.00,Ohio,L,Green,Winter,4.9,No,Standard,No,33.0,Venmo,Fortnightly
152,749,35,Male,Hat,Accessories,39.00,South Dakota,L,Brown,Fall,3.9,Yes,Free Shipping,Yes,8.0,Bank Transfer,Quarterly
153,2507,57,Male,Dress,Clothing,82.00,New York,XL,Orange,Spring,4.4,No,Free Shipping,No,19.0,Venmo,Annually
154,1285,65,Male,Dress,Clothing,93.00,Arkansas,M,Black,Spring,3.9,No,Express,Yes,38.0,PayPal,Fortnightly
155,4047,49,Male,Watch,Electronics,NaN,Phoenix,NaN,White,Summer,5.0,Yes,Standard,No,NaN,Cash,Weekly
156,5014,60,Female,Shirt,Accessories,NaN,Phoenix,S,Green,Winter,2.0,Yes,Standard,Yes,44.0,Debit Card,Monthly
157,1195,50,Male,Hoodie,Clothing,46.00,New York,S,Teal,Winter,3.1,No,2-Day Shipping,Yes,6.0,Credit Card,Fortnightly
158,2013,48,Male,Jeans,Clothing,53.00,Nevada,L,Green,Fall,3.2,No,Store Pickup,No,5.0,Cash,Fortnightly
159,4076,57,Other,Watch,Clothing,NaN,Phoenix,M,White,Summer,2.0,No,Express,No,38.0,Credit Card,Weekly
160,2050,68,Male,Boots,Footwear,24.00,Rhode Island,L,Blue,Fall,2.7,No,Standard,No,15.0,Venmo,Annually
161,1306,31,Male,Pants,Clothing,56.00,Mississippi,XL,Peach,Spring,4.5,No,Express,Yes,2.0,PayPal,Every 3 Months
162,5024,38,Other,Bag,Electronics,NaN,Los Angeles,NaN,Green,Summer,NaN,Yes,Express,Yes,NaN,Debit Card,Quarterly
163,3170,35,Female,T-shirt,Clothing,59.00,Georgia,M,White,Fall,3.8,No,Free Shipping,No,3.0,Venmo,Weekly
164,1116,30,Male,Hat,Accessories,58.00,New York,S,Peach,Fall,4.0,No,2-Day Shipping,Yes,37.0,Cash,Weekly
165,2317,28,Male,Sneakers,Footwear,39.00,Montana,L,Yellow,Winter,3.8,No,Standard,No,7.0,Debit Card,Annually
166,728,62,Male,Sweater,Clothing,97.00,Arkansas,S,Gray,Winter,4.8,Yes,Next Day Air,Yes,37.0,Venmo,Every 3 Months
167,467,38,Male,Jeans,Clothing,24.00,Vermont,L,Turquoise,Winter,4.6,Yes,Free Shipping,Yes,25.0,PayPal,Weekly
168,4235,56,Other,Headphones,Clothing,NaN,New York,S,Red,Spring,NaN,Yes,Express,Yes,NaN,Debit Card,Quarterly
169,656,20,Male,Handbag,Accessories,36.00,Mississippi,S,Purple,Fall,3.1,Yes,Free Shipping,Yes,19.0,Venmo,Monthly
170,4542,28,Other,Shoes,Electronics,NaN,Houston,NaN,Red,Summer,NaN,Yes,Express,No,NaN,PayPal,Weekly
171,99,20,Male,Jeans,Clothing,67.00,New York,XL,Teal,Spring,2.6,Yes,Next Day Air,Yes,20.0,Bank Transfer,Annually
172,3681,22,Female,Sunglasses,Accessories,36.00,Iowa,S,Blue,Winter,2.9,No,Standard,No,30.0,Debit Card,Quarterly
173,3715,18,Female,Hat,Accessories,31.00,New York,S,Peach,Winter,3.9,No,Express,No,35.0,Credit Card,Weekly
174,2726,64,Female,Backpack,Accessories,99.00,Mississippi,S,Violet,Summer,2.7,No,Free Shipping,No,4.0,Debit Card,Annually
175,2544,27,Male,Scarf,Accessories,56.00,West Virginia,L,Peach,Spring,2.7,No,Next Day Air,No,30.0,PayPal,Bi-Weekly
176,2834,43,Female,Jeans,Clothing,56.00,Arkansas,M,Teal,Fall,3.3,No,Free Shipping,No,19.0,Cash,Monthly
177,1084,35,Male,Backpack,Accessories,97.00,Washington,L,Teal,Summer,3.3,No,Store Pickup,Yes,43.0,Cash,Weekly
178,2904,38,Female,Scarf,Accessories,39.00,Delaware,S,Teal,Spring,3.5,No,2-Day Shipping,No,24.0,Credit Card,Every 3 Months
179,964,21,Male,Boots,Footwear,63.00,South Carolina,L,Green,Spring,2.5,Yes,2-Day Shipping,Yes,14.0,Credit Card,Weekly

In [22]:
df.loc[df['Category']=='Electronics','Size']="Not Applicable"

In [23]:
df[df['Category']=='Electronics']

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
12,4776,64,Other,Laptop,Electronics,884.04,Los Angeles,Not Applicable,Black,Spring,NaN,No,Express,No,NaN,Credit Card,Quarterly
20,4256,70,Male,Phone,Electronics,NaN,Los Angeles,Not Applicable,Green,Autumn,NaN,Yes,Standard,Yes,25.0,Cash,Weekly
38,4418,67,Female,Watch,Electronics,NaN,Los Angeles,Not Applicable,Red,Autumn,NaN,No,Express,No,47.0,PayPal,Quarterly
49,4319,47,Other,Watch,Electronics,NaN,Houston,Not Applicable,Green,Summer,NaN,Yes,Express,Yes,28.0,PayPal,Monthly
51,4708,33,Female,Bag,Electronics,NaN,New York,Not Applicable,Green,Winter,4.0,Yes,Standard,Yes,31.0,Debit Card,Quarterly
52,4827,20,Female,Laptop,Electronics,NaN,Houston,Not Applicable,Green,Summer,NaN,No,Express,No,17.0,Debit Card,Monthly
74,4292,27,Other,Laptop,Electronics,NaN,Houston,Not Applicable,Blue,Summer,NaN,Yes,Express,Yes,NaN,Credit Card,Weekly
97,4587,52,Male,Laptop,Electronics,1392.02,Phoenix,Not Applicable,White,Winter,2.0,Yes,Standard,Yes,NaN,Cash,Quarterly
98,4057,41,Female,Shoes,Electronics,NaN,Los Angeles,Not Applicable,Black,Winter,NaN,No,Standard,Yes,10.0,Credit Card,Quarterly
129,4530,20,Male,Watch,Electronics,532.49,New York,Not Applicable,Black,Autumn,NaN,Yes,Standard,Yes,NaN,Debit Card,Monthly
140,5058,63,Other,Shirt,Electronics,1342.62,Los Angeles,Not Applicable,Blue,Spring,4.0,Yes,Standard,Yes,NaN,PayPal,Quarterly
143,4192,46,Other,Watch,Electronics,105.21,Houston,Not Applicable,Green,Winter,NaN,Yes,Standard,Yes,NaN,PayPal,Monthly
155,4047,49,Male,Watch,Electronics,NaN,Phoenix,Not Applicable,White,Summer,5.0,Yes,Standard,No,NaN,Cash,Weekly
162,5024,38,Other,Bag,Electronics,NaN,Los Angeles,Not Applicable,Green,Summer,NaN,Yes,Express,Yes,NaN,Debit Card,Quarterly
170,4542,28,Other,Shoes,Electronics,NaN,Houston,Not Applicable,Red,Summer,NaN,Yes,Express,No,NaN,PayPal,Weekly
196,4571,40,Other,Shirt,Electronics,450.41,New York,Not Applicable,Black,Autumn,5.0,Yes,Standard,Yes,NaN,Cash,Quarterly
201,4843,22,Female,Phone,Electronics,854.96,Los Angeles,Not Applicable,Red,Winter,NaN,No,Standard,Yes,32.0,PayPal,Quarterly
207,5083,42,Other,Shoes,Electronics,758.10,Houston,Not Applicable,White,Autumn,NaN,No,Standard,No,48.0,PayPal,Quarterly
209,4079,28,Male,Shoes,Electronics,1438.53,Chicago,Not Applicable,White,Spring,1.0,Yes,Standard,Yes,15.0,Cash,Monthly
252,5027,39,Male,Headphones,Electronics,1430.07,Houston,Not Applicable,Blue,Winter,2.0,No,Standard,No,NaN,Cash,Weekly
292,4794,52,Female,Phone,Electronics,NaN,Phoenix,Not Applicable,White,Spring,NaN,No,Express,Yes,41.0,Credit Card,Weekly
304,4643,50,Male,Phone,Electronics,NaN,Phoenix,Not Applicable,Blue,Winter,2.0,Yes,Express,No,44.0,Debit Card,Monthly
316,4863,24,Female,Watch,Electronics,NaN,New York,Not Applicable,Green,Autumn,NaN,Yes,Express,Yes,NaN,Cash,Monthly
333,4561,53,Male,Bag,Electronics,82.06,Los Angeles,Not Applicable,Green,Summer,5.0,No,Standard,Yes,8.0,Cash,Weekly
351,4316,23,Female,Headphones,Electronics,NaN,New York,Not Applicable,Green,Autumn,1.0,No,Standard,No,NaN,Credit Card,Weekly
354,4450,20,Male,Shoes,Electronics,NaN,Los Angeles,Not Applicable,Black,Autumn,NaN,No,Express,No,NaN,Credit Card,Monthly
357,4846,34,Female,Phone,Electronics,719.91,Los Angeles,Not Applicable,Blue,Spring,NaN,No,Standard,Yes,NaN,Debit Card,Monthly
363,4567,54,Female,Shoes,Electronics,NaN,Chicago,Not Applicable,Black,Summer,3.0,No,Standard,No,31.0,Credit Card,Monthly
394,4074,61,Female,Bag,Electronics,316.21,Los Angeles,Not Applicable,Red,Winter,1.0,Yes,Express,No,15.0,Debit Card,Monthly
397,4790,56,Other,Headphones,Electronics,685.22,Phoenix,Not Applicable,Blue,Summer,4.0,No,Express,Yes,NaN,Cash,Weekly
419,4343,48,Other,Bag,Electronics,NaN,Los Angeles,Not Applicable,Blue,Summer,NaN,No,Standard,Yes,26.0,Debit Card,Weekly
420,4023,55,Other,Bag,Electronics,NaN,Phoenix,Not Applicable,White,Spring,3.0,Yes,Express,No,NaN,Debit Card,Weekly
467,4427,23,Female,Shoes,Electronics,638.81,Houston,Not Applicable,White,Autumn,NaN,Yes,Express,No,1.0,PayPal,Weekly
470,4748,26,Male,Phone,Electronics,571.08,Houston,Not Applicable,Green,Autumn,5.0,No,Standard,No,NaN,Debit Card,Quarterly
493,4630,25,Female,Bag,Electronics,468.46,Chicago,Not Applicable,Red,Winter,NaN,No,Standard,No,50.0,Credit Card,Quarterly
494,4003,69,Other,Shoes,Electronics,1426.64,Chicago,Not Applicable,Black,Autumn,3.0,Yes,Standard,Yes,19.0,Cash,Monthly
565,4697,46,Female,Watch,Electronics,NaN,Phoenix,Not Applicable,White,Winter,NaN,No,Standard,No,NaN,Credit Card,Weekly
578,4520,60,Male,Watch,Electronics,921.94,Chicago,Not Applicable,Blue,Autumn,NaN,Yes,Standard,Yes,NaN,Credit Card,Monthly
591,4395,40,Male,Watch,Electronics,104.65,Chicago,Not Applicable,Green,Spring,1.0,No,Standard,No,36.0,Credit Card,Quarterly
600,4785,53,Female,Bag,Electronics,NaN,Phoenix,Not Applicable,Green,Autumn,NaN,No,Standard,No,NaN,Cash,Weekly
603,4533,43,Female,Shoes,Electronics,NaN,Houston,Not Applicable,Black,Summer,1.0,No,Express,No,3.0,Debit Card,Monthly
606,4053,54,Female,Shoes,Electronics,370.41,Chicago,Not Applicable,Blue,Summer,NaN,Yes,Standard,No,9.0,Debit Card,Weekly
618,4995,34,Female,Laptop,Electronics,NaN,Los Angeles,Not Applicable,Black,Autumn,NaN,No,Standard,No,6.0,Cash,Quarterly
631,4717,38,Female,Shirt,Electronics,NaN,New York,Not Applicable,Black,Autumn,4.0,Yes,Standard,Yes,0.0,Cash,Quarterly
632,4373,40,Female,Headphones,Electronics,767.36,Chicago,Not Applicable,Black,Spring,NaN,No,Express,Yes,NaN,PayPal,Quarterly
634,4052,47,Female,Phone,Electronics,NaN,New York,Not Applicable,White,Winter,2.0,Yes,Standard,Yes,NaN,Debit Card,Monthly
640,5057,33,Male,Shirt,Electronics,1103.36,Los Angeles,Not Applicable,Black,Summer,NaN,No,Standard,Yes,6.0,Credit Card,Monthly
647,4017,58,Male,Laptop,Electronics,690.65,Phoenix,Not Applicable,Green,Autumn,1.0,No,Standard,No,NaN,Debit Card,Monthly
668,4234,27,Male,Laptop,Electronics,1388.53,Chicago,Not Applicable,Blue,Summer,NaN,Yes,Express,No,45.0,PayPal,Quarterly
674,4299,61,Female,Watch,Electronics,NaN,Phoenix,Not Applicable,Black,Spring,4.0,No,Standard,No,NaN,Debit Card,Quarterly
678,4070,58,Female,Watch,Electronics,939.30,Los Angeles,Not Applicable,Green,Spring,NaN,No,Express,No,NaN,Debit Card,Weekly
713,4363,25,Female,Headphones,Electronics,NaN,Houston,Not Applicable,Red,Autumn,NaN,No,Express,Yes,NaN,PayPal,Weekly
714,4048,30,Other,Phone,Electronics,NaN,Los Angeles,Not Applicable,Green,Summer,NaN,No,Standard,Yes,6.0,PayPal,Quarterly
737,4674,21,Female,Phone,Electronics,310.29,Chicago,Not Applicable,White,Spring,1.0,No,Express,Yes,4.0,Debit Card,Weekly
756,4028,23,Other,Headphones,Electronics,NaN,Los Angeles,Not Applicable,Black,Summer,NaN,Yes,Express,Yes,NaN,Credit Card,Quarterly
759,4929,58,Female,Bag,Electronics,607.15,Houston,Not Applicable,Blue,Autumn,NaN,Yes,Standard,No,38.0,Debit Card,Quarterly
776,5017,20,Other,Headphones,Electronics,193.65,Chicago,Not Applicable,Blue,Winter,NaN,No,Express,Yes,NaN,Credit Card,Monthly
797,4949,39,Other,Watch,Electronics,119.25,New York,Not Applicable,White,Summer,NaN,Yes,Express,No,28.0,Cash,Monthly
821,4951,34,Male,Phone,Electronics,NaN,Phoenix,Not Applicable,Black,Spring,1.0,No,Express,No,NaN,Cash,Monthly
873,4207,44,Other,Bag,Electronics,896.53,New York,Not Applicable,Blue,Winter,4.0,Yes,Express,No,0.0,Debit Card,Monthly
880,4688,61,Female,Headphones,Electronics,NaN,Houston,Not Applicable,Black,Winter,4.0,No,Standard,No,40.0,Credit Card,Monthly
894,4627,54,Female,Laptop,Electronics,860.91,Houston,Not Applicable,Black,Summer,NaN,No,Express,Yes,16.0,Cash,Quarterly
900,4333,32,Female,Shirt,Electronics,NaN,Los Angeles,Not Applicable,Blue,Winter,NaN,No,Express,Yes,NaN,Credit Card,Quarterly
906,4593,56,Other,Shoes,Electronics,NaN,New York,Not Applicable,Blue,Winter,NaN,No,Express,Yes,11.0,Debit Card,Monthly
913,4725,59,Other,Shirt,Electronics,175.40,Phoenix,Not Applicable,White,Spring,NaN,Yes,Standard,Yes,47.0,Cash,Quarterly
918,4138,40,Female,Shirt,Electronics,780.59,Los Angeles,Not Applicable,Blue,Autumn,NaN,No,Standard,No,NaN,PayPal,Weekly
972,4143,18,Other,Bag,Electronics,NaN,Houston,Not Applicable,Red,Spring,NaN,Yes,Standard,No,6.0,Debit Card,Weekly
998,4125,20,Other,Headphones,Electronics,543.93,Phoenix,Not Applicable,Black,Summer,5.0,No,Express,No,37.0,Cash,Weekly
1004,4611,66,Other,Shoes,Electronics,NaN,Houston,Not Applicable,Red,Summer,1.0,No,Express,Yes,34.0,Credit Card,Quarterly
1014,4614,56,Female,Shoes,Electronics,NaN,Chicago,Not Applicable,Red,Spring,NaN,No,Standard,Yes,NaN,Debit Card,Quarterly
1023,4885,51,Male,Watch,Electronics,1459.71,New York,Not Applicable,Blue,Summer,5.0,Yes,Express,No,NaN,PayPal,Quarterly
1058,4107,48,Male,Bag,Electronics,236.32,Houston,Not Applicable,Red,Spring,NaN,Yes,Express,No,NaN,Debit Card,Monthly
1063,4572,45,Male,Bag,Electronics,1270.13,New York,Not Applicable,Red,Autumn,1.0,No,Standard,No,3.0,Debit Card,Weekly
1069,5038,43,Other,Phone,Electronics,851.29,Los Angeles,Not Applicable,Green,Winter,NaN,No,Standard,No,0.0,PayPal,Weekly
1094,5069,25,Male,Shoes,Electronics,NaN,New York,Not Applicable,Blue,Winter,4.0,No,Standard,No,NaN,Credit Card,Weekly
1097,4109,64,Female,Bag,Electronics,NaN,New York,Not Applicable,White,Winter,1.0,No,Express,Yes,NaN,Debit Card,Monthly
1099,4341,57,Other,Bag,Electronics,NaN,Phoenix,Not Applicable,Black,Summer,NaN,Yes,Standard,Yes,NaN,Credit Card,Weekly
1119,5033,46,Female,Phone,Electronics,NaN,New York,Not Applicable,Red,Winter,5.0,Yes,Standard,Yes,48.0,Credit Card,Monthly
1143,4879,59,Other,Shirt,Electronics,NaN,Chicago,Not Applicable,Blue,Autumn,NaN,Yes,Standard,No,24.0,PayPal,Monthly
1151,4264,60,Male,Watch,Electronics,NaN,Houston,Not Applicable,Black,Summer,2.0,Yes,Express,Yes,NaN,Cash,Quarterly
1162,4128,41,Female,Shoes,Electronics,NaN,Houston,Not Applicable,Red,Autumn,NaN,No,Express,No,NaN,Credit Card,Monthly
1165,5092,38,Male,Headphones,Electronics,NaN,Phoenix,Not Applicable,Blue,Winter,NaN,Yes,Express,No,NaN,Debit Card,Quarterly
1169,4659,20,Female,Headphones,Electronics,NaN,New York,Not Applicable,Blue,Autumn,NaN,Yes,Standard,Yes,NaN,Cash,Weekly
1183,4726,65,Other,Laptop,Electronics,NaN,Los Angeles,Not Applicable,White,Autumn,NaN,Yes,Express,Yes,35.0,Credit Card,Weekly
1190,4498,18,Female,Watch,Electronics,NaN,Phoenix,Not Applicable,White,Autumn,5.0,No,Standard,No,15.0,Credit Card,Weekly
1194,4270,55,Female,Phone,Electronics,387.35,Los Angeles,Not Applicable,White,Winter,NaN,No,Standard,No,9.0,Credit Card,Quarterly
1205,4000,33,Other,Headphones,Electronics,NaN,Phoenix,Not Applicable,Red,Spring,5.0,Yes,Express,Yes,47.0,PayPal,Quarterly
1210,4351,26,Other,Watch,Electronics,1147.10,Chicago,Not Applicable,White,Winter,2.0,No,Standard,Yes,NaN,Credit Card,Weekly
1217,4318,45,Female,Watch,Electronics,335.78,New York,Not Applicable,White,Spring,2.0,No,Standard,Yes,6.0,Debit Card,Monthly
1232,4215,70,Male,Phone,Electronics,NaN,New York,Not Applicable,Red,Summer,NaN,No,Standard,Yes,25.0,PayPal,Quarterly
1260,4754,37,Male,Phone,Electronics,NaN,Chicago,Not Applicable,Black,Winter,NaN,No,Express,Yes,NaN,Cash,Quarterly
1268,4500,22,Female,Bag,Electronics,NaN,Phoenix,Not Applicable,Black,Winter,NaN,No,Standard,Yes,39.0,Credit Card,Weekly
1277,4164,41,Female,Phone,Electronics,NaN,New York,Not Applicable,Red,Spring,NaN,No,Standard,No,NaN,PayPal,Monthly
1302,4955,20,Other,Watch,Electronics,NaN,Los Angeles,Not Applicable,Red,Winter,NaN,No,Express,No,3.0,Cash,Quarterly
1326,4616,51,Female,Shirt,Electronics,336.09,New York,Not Applicable,White,Autumn,NaN,No,Express,Yes,NaN,PayPal,Monthly
1349,4641,30,Female,Laptop,Electronics,822.03,Los Angeles,Not Applicable,Red,Summer,NaN,No,Express,Yes,NaN,Debit Card,Weekly
1368,4296,59,Female,Shirt,Electronics,591.76,New York,Not Applicable,White,Winter,3.0,No,Standard,No,4.0,Credit Card,Quarterly
1377,4080,28,Female,Bag,Electronics,551.22,Los Angeles,Not Applicable,Blue,Winter,NaN,Yes,Standard,Yes,32.0,Cash,Monthly
1385,4476,56,Male,Shirt,Electronics,NaN,Phoenix,Not Applicable,White,Autumn,1.0,No,Express,Yes,NaN,Debit Card,Monthly
1418,4470,60,Female,Shoes,Electronics,NaN,Phoenix,Not Applicable,Red,Autumn,3.0,No,Express,Yes,NaN,Cash,Weekly
1420,5039,61,Male,Shoes,Electronics,835.52,Los Angeles,Not Applicable,Blue,Autumn,5.0,No,Standard,No,5.0,Debit Card,Monthly
1434,4436,59,Female,Shirt,Electronics,NaN,Los Angeles,Not Applicable,Red,Summer,NaN,Yes,Express,Yes,39.0,PayPal,Monthly
1469,4445,59,Male,Laptop,Electronics,NaN,Houston,Not Applicable,Red,Summer,NaN,Yes,Standard,No,46.0,Credit Card,Monthly
1475,4598,37,Female,Laptop,Electronics,187.51,Phoenix,Not Applicable,Blue,Summer,NaN,Yes,Standard,Yes,20.0,Credit Card,Weekly
1486,4088,49,Female,Laptop,Electronics,NaN,Chicago,Not Applicable,Blue,Spring,NaN,No,Express,No,37.0,Debit Card,Weekly
1489,4304,35,Female,Headphones,Electronics,469.48,Houston,Not Applicable,Red,Winter,NaN,Yes,Standard,Yes,NaN,Cash,Monthly
1521,4670,41,Male,Shirt,Electronics,NaN,Chicago,Not Applicable,Blue,Autumn,NaN,No,Express,Yes,NaN,PayPal,Quarterly
1529,5099,59,Female,Phone,Electronics,736.01,Chicago,Not Applicable,White,Spring,1.0,No,Express,Yes,NaN,Cash,Weekly
1550,4377,34,Female,Shoes,Electronics,NaN,Chicago,Not Applicable,Green,Autumn,NaN,No,Express,No,3.0,Debit Card,Weekly
1559,4124,46,Other,Shirt,Electronics,NaN,Houston,Not Applicable,Red,Winter,NaN,No,Express,Yes,NaN,Credit Card,Monthly
1566,4269,56,Female,Laptop,Electronics,118.61,Los Angeles,Not Applicable,Green,Autumn,1.0,Yes,Standard,Yes,NaN,PayPal,Quarterly
1594,4945,59,Female,Shirt,Electronics,1343.37,Phoenix,Not Applicable,Red,Summer,2.0,No,Standard,Yes,NaN,Credit Card,Weekly
1624,4437,28,Male,Shoes,Electronics,412.80,Phoenix,Not Applicable,Green,Autumn,NaN,Yes,Standard,Yes,NaN,Credit Card,Quarterly
1627,4634,49,Female,Phone,Electronics,NaN,Chicago,Not Applicable,Red,Summer,NaN,No,Standard,Yes,NaN,Cash,Quarterly
1681,4455,46,Female,Watch,Electronics,NaN,New York,Not Applicable,Blue,Spring,NaN,No,Standard,No,23.0,Debit Card,Quarterly
1693,4469,22,Female,Watch,Electronics,639.97,Chicago,Not Applicable,Blue,Spring,1.0,No,Express,Yes,NaN,Cash,Monthly
1722,5081,37,Other,Bag,Electronics,1103.56,Phoenix,Not Applicable,Green,Autumn,3.0,No,Standard,No,17.0,Debit Card,Weekly
1729,5005,60,Male,Phone,Electronics,NaN,Chicago,Not Applicable,Black,Spring,NaN,No,Express,No,NaN,Cash,Weekly
1737,4322,54,Other,Shirt,Electronics,NaN,Los Angeles,Not Applicable,Green,Spring,5.0,No,Standard,Yes,43.0,Debit Card,Weekly
1743,4923,67,Male,Shoes,Electronics,NaN,Phoenix,Not Applicable,Blue,Summer,NaN,Yes,Standard,No,NaN,Cash,Weekly
1746,4721,54,Male,Phone,Electronics,726.15,Chicago,Not Applicable,Green,Summer,NaN,Yes,Express,Yes,NaN,Cash,Quarterly
1748,4760,41,Other,Laptop,Electronics,NaN,Chicago,Not Applicable,White,Summer,5.0,Yes,Express,Yes,NaN,Debit Card,Weekly
1794,4431,25,Male,Phone,Electronics,716.34,New York,Not Applicable,Blue,Summer,5.0,No,Standard,Yes,33.0,PayPal,Weekly
1845,5070,37,Other,Phone,Electronics,NaN,Los Angeles,Not Applicable,Black,Autumn,2.0,No,Standard,No,5.0,Debit Card,Quarterly
1884,4714,55,Female,Phone,Electronics,NaN,Houston,Not Applicable,Black,Autumn,NaN,No,Express,No,NaN,Credit Card,Monthly
1930,4619,28,Other,Phone,Electronics,NaN,Los Angeles,Not Applicable,Black,Autumn,NaN,No,Standard,No,NaN,Debit Card,Monthly
1947,4867,23,Female,Shoes,Electronics,1391.62,New York,Not Applicable,Red,Winter,NaN,Yes,Standard,No,4.0,Credit Card,Quarterly
1948,4687,44,Other,Shoes,Electronics,NaN,Chicago,Not Applicable,Blue,Autumn,NaN,Yes,Express,No,9.0,Debit Card,Monthly
1949,4599,31,Male,Watch,Electronics,NaN,New York,Not Applicable,Black,Winter,NaN,Yes,Standard,No,NaN,Debit Card,Quarterly
1958,4329,31,Other,Bag,Electronics,1380.81,Phoenix,Not Applicable,White,Autumn,NaN,No,Express,Yes,37.0,Credit Card,Monthly
1965,4208,36,Female,Bag,Electronics,178.86,Houston,Not Applicable,White,Winter,3.0,Yes,Express,No,NaN,Credit Card,Monthly
1970,4703,21,Other,Headphones,Electronics,784.80,Los Angeles,Not Applicable,White,Winter,NaN,No,Standard,Yes,NaN,Debit Card,Quarterly
1971,4026,58,Other,Bag,Electronics,NaN,Houston,Not Applicable,White,Spring,NaN,No,Express,No,NaN,Debit Card,Weekly
1972,5068,68,Female,Shoes,Electronics,NaN,Los Angeles,Not Applicable,Black,Winter,NaN,Yes,Standard,Yes,NaN,Debit Card,Quarterly
1987,4832,19,Female,Bag,Electronics,322.81,Houston,Not Applicable,Green,Winter,1.0,Yes,Express,No,11.0,PayPal,Quarterly
1993,4632,39,Male,Phone,Electronics,71.87,Chicago,Not Applicable,White,Spring,4.0,Yes,Standard,No,10.0,Cash,Quarterly
2000,4882,35,Other,Bag,Electronics,1183.94,New York,Not Applicable,Blue,Autumn,NaN,Yes,Express,Yes,13.0,Credit Card,Quarterly
2006,4180,50,Male,Watch,Electronics,NaN,New York,Not Applicable,Green,Winter,NaN,No,Express,No,42.0,PayPal,Quarterly
2016,4821,54,Other,Headphones,Electronics,NaN,New York,Not Applicable,White,Autumn,1.0,Yes,Express,Yes,NaN,Cash,Quarterly
2019,4753,48,Other,Watch,Electronics,136.29,New York,Not Applicable,White,Autumn,NaN,Yes,Standard,No,NaN,Credit Card,Quarterly
2029,4872,56,Female,Laptop,Electronics,NaN,Chicago,Not Applicable,Red,Autumn,3.0,No,Express,No,46.0,Credit Card,Monthly
2041,5073,34,Female,Bag,Electronics,NaN,New York,Not Applicable,Blue,Autumn,NaN,Yes,Standard,No,NaN,PayPal,Monthly
2058,4730,70,Male,Watch,Electronics,NaN,Chicago,Not Applicable,Green,Winter,NaN,Yes,Express,No,NaN,Cash,Quarterly
2085,4415,20,Female,Watch,Electronics,347.82,Phoenix,Not Applicable,Black,Winter,NaN,Yes,Standard,Yes,39.0,Debit Card,Monthly
2091,4186,54,Other,Shirt,Electronics,NaN,New York,Not Applicable,Black,Autumn,5.0,No,Express,Yes,23.0,PayPal,Monthly
2108,4464,52,Female,Phone,Electronics,NaN,Chicago,Not Applicable,Blue,Summer,NaN,No,Standard,Yes,1.0,Debit Card,Weekly
2126,4094,36,Female,Watch,Electronics,630.40,Houston,Not Applicable,White,Spring,5.0,No,Express,No,34.0,PayPal,Weekly
2130,4344,31,Female,Headphones,Electronics,23.30,Los Angeles,Not Applicable,Red,Spring,NaN,Yes,Standard,No,39.0,PayPal,Quarterly
2147,4777,41,Male,Phone,Electronics,NaN,Chicago,Not Applicable,White,Winter,NaN,Yes,Express,Yes,NaN,Credit Card,Monthly
2163,4968,27,Male,Watch,Electronics,897.39,New York,Not Applicable,Black,Summer,1.0,No,Standard,No,NaN,PayPal,Monthly
2164,4246,57,Male,Bag,Electronics,NaN,Houston,Not Applicable,Blue,Winter,5.0,No,Express,Yes,NaN,Debit Card,Quarterly
2165,4314,42,Female,Watch,Electronics,866.03,Los Angeles,Not Applicable,Black,Autumn,3.0,Yes,Express,No,NaN,Debit Card,Weekly
2181,4698,42,Other,Watch,Electronics,643.00,New York,Not Applicable,White,Autumn,2.0,Yes,Express,Yes,NaN,PayPal,Weekly
2183,4813,66,Other,Watch,Electronics,NaN,New York,Not Applicable,White,Autumn,NaN,No,Standard,Yes,47.0,Debit Card,Quarterly
2201,4600,60,Other,Phone,Electronics,1460.51,Chicago,Not Applicable,White,Summer,2.0,No,Standard,Yes,20.0,Cash,Quarterly
2204,4864,25,Female,Shoes,Electronics,NaN,Houston,Not Applicable,Red,Autumn,NaN,Yes,Express,Yes,37.0,Debit Card,Quarterly
2212,4471,35,Other,Laptop,Electronics,NaN,Los Angeles,Not Applicable,Blue,Autumn,3.0,No,Standard,Yes,NaN,Cash,Quarterly
2220,4833,46,Female,Headphones,Electronics,NaN,Chicago,Not Applicable,Black,Spring,NaN,Yes,Standard,No,31.0,Debit Card,Weekly
2237,4522,51,Male,Phone,Electronics,750.93,Houston,Not Applicable,Red,Autumn,NaN,No,Express,No,35.0,Debit Card,Monthly
2249,4037,23,Female,Laptop,Electronics,109.58,Houston,Not Applicable,Black,Summer,NaN,Yes,Standard,No,NaN,PayPal,Weekly
2250,4039,35,Female,Watch,Electronics,NaN,Los Angeles,Not Applicable,Green,Spring,3.0,Yes,Express,Yes,24.0,Cash,Monthly
2254,4068,42,Male,Shirt,Electronics,357.92,Phoenix,Not Applicable,Green,Winter,NaN,No,Standard,Yes,0.0,Cash,Monthly
2264,4147,56,Other,Bag,Electronics,752.44,Phoenix,Not Applicable,Black,Summer,1.0,No,Express,Yes,14.0,Cash,Quarterly
2274,4059,27,Male,Bag,Electronics,NaN,Chicago,Not Applicable,White,Autumn,NaN,Yes,Standard,Yes,36.0,PayPal,Quarterly

In [24]:
df.groupby('Category')['Size'].unique()

Category
Accessories       [M, L, S, XL]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear          [M, L, S, XL]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

In [38]:
df[df['Item Purchased']=='Bag']

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
35,5042,46,Other,Bag,Clothing,NaN,Los Angeles,M,White,Summer,3.168539,Yes,Express,No,31.0,PayPal,Monthly
39,4894,24,Other,Bag,Accessories,NaN,Los Angeles,L,Red,Spring,3.168539,No,Standard,No,4.0,PayPal,Quarterly
51,4708,33,Female,Bag,Electronics,NaN,New York,Not Applicable,Green,Winter,4.000000,Yes,Standard,Yes,31.0,Debit Card,Quarterly
72,4558,41,Other,Bag,Accessories,208.02,Los Angeles,M,White,Autumn,3.168539,No,Standard,Yes,NaN,PayPal,Monthly
109,4972,46,Other,Bag,Accessories,34.65,New York,M,White,Autumn,4.000000,No,Express,Yes,3.0,Debit Card,Monthly
162,5024,38,Other,Bag,Electronics,NaN,Los Angeles,Not Applicable,Green,Summer,3.168539,Yes,Express,Yes,NaN,Debit Card,Quarterly
212,4257,60,Other,Bag,Clothing,NaN,Houston,XL,Green,Winter,3.168539,Yes,Express,No,11.0,Cash,Quarterly
262,4214,34,Other,Bag,Accessories,NaN,Phoenix,S,Red,Autumn,1.000000,Yes,Express,No,15.0,PayPal,Monthly
276,4557,51,Other,Bag,Accessories,187.34,Los Angeles,S,Blue,Spring,3.168539,Yes,Express,Yes,NaN,PayPal,Weekly
328,4905,41,Female,Bag,Accessories,NaN,Los Angeles,M,White,Spring,3.168539,No,Standard,Yes,NaN,PayPal,Quarterly
333,4561,53,Male,Bag,Electronics,82.06,Los Angeles,Not Applicable,Green,Summer,5.000000,No,Standard,Yes,8.0,Cash,Weekly
338,4625,49,Male,Bag,Accessories,1002.35,New York,S,Blue,Summer,3.000000,Yes,Express,No,NaN,Cash,Weekly
374,4120,65,Other,Bag,Clothing,NaN,Chicago,S,Green,Winter,3.168539,Yes,Standard,No,NaN,Debit Card,Monthly
381,4496,22,Male,Bag,Accessories,1246.93,Chicago,S,Red,Spring,1.000000,Yes,Standard,No,45.0,Credit Card,Monthly
394,4074,61,Female,Bag,Electronics,316.21,Los Angeles,Not Applicable,Red,Winter,1.000000,Yes,Express,No,15.0,Debit Card,Monthly
419,4343,48,Other,Bag,Electronics,NaN,Los Angeles,Not Applicable,Blue,Summer,3.168539,No,Standard,Yes,26.0,Debit Card,Weekly
420,4023,55,Other,Bag,Electronics,NaN,Phoenix,Not Applicable,White,Spring,3.000000,Yes,Express,No,NaN,Debit Card,Weekly
461,4799,48,Male,Bag,Clothing,1170.25,Phoenix,M,Blue,Winter,3.000000,No,Express,Yes,NaN,Debit Card,Weekly
472,4544,45,Other,Bag,Accessories,253.94,Chicago,L,Green,Winter,2.000000,Yes,Standard,Yes,28.0,Debit Card,Quarterly
493,4630,25,Female,Bag,Electronics,468.46,Chicago,Not Applicable,Red,Winter,3.168539,No,Standard,No,50.0,Credit Card,Quarterly
523,4401,49,Other,Bag,Accessories,NaN,Phoenix,L,Green,Winter,4.000000,No,Express,Yes,32.0,Cash,Quarterly
595,5002,24,Other,Bag,Accessories,781.26,Houston,L,Green,Summer,3.168539,Yes,Standard,Yes,41.0,Cash,Weekly
600,4785,53,Female,Bag,Electronics,NaN,Phoenix,Not Applicable,Green,Autumn,3.168539,No,Standard,No,NaN,Cash,Weekly
639,4432,29,Other,Bag,Accessories,1311.75,New York,L,Blue,Summer,3.168539,No,Standard,No,47.0,Debit Card,Weekly
715,4346,21,Female,Bag,Clothing,NaN,Chicago,XL,Blue,Autumn,1.000000,Yes,Standard,Yes,28.0,Cash,Monthly
759,4929,58,Female,Bag,Electronics,607.15,Houston,Not Applicable,Blue,Autumn,3.168539,Yes,Standard,No,38.0,Debit Card,Quarterly
846,4720,69,Male,Bag,Clothing,611.08,New York,XL,Black,Summer,3.168539,No,Standard,No,46.0,PayPal,Weekly
848,4036,41,Male,Bag,Accessories,NaN,Phoenix,M,Black,Summer,5.000000,No,Standard,No,48.0,Cash,Quarterly
873,4207,44,Other,Bag,Electronics,896.53,New York,Not Applicable,Blue,Winter,4.000000,Yes,Express,No,0.0,Debit Card,Monthly
928,4884,43,Other,Bag,Clothing,489.56,Chicago,M,Red,Spring,2.000000,No,Standard,Yes,32.0,Debit Card,Weekly
953,4956,69,Other,Bag,Clothing,843.80,Houston,XL,Blue,Autumn,4.000000,Yes,Standard,No,NaN,Debit Card,Monthly
972,4143,18,Other,Bag,Electronics,NaN,Houston,Not Applicable,Red,Spring,3.168539,Yes,Standard,No,6.0,Debit Card,Weekly
1058,4107,48,Male,Bag,Electronics,236.32,Houston,Not Applicable,Red,Spring,3.168539,Yes,Express,No,NaN,Debit Card,Monthly
1063,4572,45,Male,Bag,Electronics,1270.13,New York,Not Applicable,Red,Autumn,1.000000,No,Standard,No,3.0,Debit Card,Weekly
1076,4426,66,Male,Bag,Clothing,NaN,Chicago,M,Blue,Summer,4.000000,Yes,Standard,Yes,0.0,Cash,Quarterly
1097,4109,64,Female,Bag,Electronics,NaN,New York,Not Applicable,White,Winter,1.000000,No,Express,Yes,NaN,Debit Card,Monthly
1099,4341,57,Other,Bag,Electronics,NaN,Phoenix,Not Applicable,Black,Summer,3.168539,Yes,Standard,Yes,NaN,Credit Card,Weekly
1259,4263,51,Female,Bag,Clothing,NaN,Houston,S,Red,Spring,4.000000,No,Express,No,17.0,Debit Card,Quarterly
1268,4500,22,Female,Bag,Electronics,NaN,Phoenix,Not Applicable,Black,Winter,3.168539,No,Standard,Yes,39.0,Credit Card,Weekly
1269,4332,31,Female,Bag,Clothing,NaN,Los Angeles,M,White,Autumn,4.000000,Yes,Standard,No,NaN,Credit Card,Quarterly
1377,4080,28,Female,Bag,Electronics,551.22,Los Angeles,Not Applicable,Blue,Winter,3.168539,Yes,Standard,Yes,32.0,Cash,Monthly
1395,4116,52,Male,Bag,Accessories,NaN,Los Angeles,L,Black,Winter,4.000000,Yes,Standard,No,NaN,Credit Card,Quarterly
1404,4174,50,Male,Bag,Clothing,NaN,New York,L,Black,Winter,5.000000,No,Standard,No,13.0,Cash,Monthly
1491,5032,24,Male,Bag,Clothing,NaN,Los Angeles,XL,Black,Autumn,2.000000,No,Express,No,31.0,Cash,Monthly
1495,4311,19,Female,Bag,Clothing,873.21,Chicago,S,Red,Winter,5.000000,Yes,Express,No,33.0,Credit Card,Monthly
1570,4989,61,Male,Bag,Accessories,NaN,Los Angeles,S,Red,Autumn,5.000000,Yes,Standard,Yes,43.0,Cash,Weekly
1610,4007,33,Male,Bag,Clothing,NaN,New York,S,Blue,Spring,1.000000,No,Standard,Yes,NaN,PayPal,Monthly
1722,5081,37,Other,Bag,Electronics,1103.56,Phoenix,Not Applicable,Green,Autumn,3.000000,No,Standard,No,17.0,Debit Card,Weekly
1732,4737,61,Other,Bag,Clothing,NaN,New York,XL,Red,Winter,5.000000,Yes,Standard,Yes,33.0,Debit Card,Quarterly
1830,5085,36,Other,Bag,Accessories,NaN,New York,S,Blue,Summer,3.168539,Yes,Standard,Yes,NaN,PayPal,Monthly
1872,4359,32,Female,Bag,Accessories,NaN,Houston,S,Green,Spring,5.000000,Yes,Standard,No,29.0,PayPal,Monthly
1909,4546,64,Other,Bag,Clothing,1200.04,Los Angeles,L,Blue,Winter,3.000000,Yes,Express,Yes,NaN,Cash,Quarterly
1958,4329,31,Other,Bag,Electronics,1380.81,Phoenix,Not Applicable,White,Autumn,3.168539,No,Express,Yes,37.0,Credit Card,Monthly
1960,5043,38,Other,Bag,Clothing,NaN,Houston,XL,Black,Winter,3.168539,No,Standard,No,NaN,Debit Card,Quarterly
1965,4208,36,Female,Bag,Electronics,178.86,Houston,Not Applicable,White,Winter,3.000000,Yes,Express,No,NaN,Credit Card,Monthly
1971,4026,58,Other,Bag,Electronics,NaN,Houston,Not Applicable,White,Spring,3.168539,No,Express,No,NaN,Debit Card,Weekly
1987,4832,19,Female,Bag,Electronics,322.81,Houston,Not Applicable,Green,Winter,1.000000,Yes,Express,No,11.0,PayPal,Quarterly
2000,4882,35,Other,Bag,Electronics,1183.94,New York,Not Applicable,Blue,Autumn,3.168539,Yes,Express,Yes,13.0,Credit Card,Quarterly
2004,4767,34,Male,Bag,Accessories,NaN,Los Angeles,M,White,Autumn,5.000000,Yes,Express,Yes,NaN,Credit Card,Monthly
2018,4917,58,Female,Bag,Clothing,120.83,Houston,L,Black,Autumn,3.000000,Yes,Express,No,3.0,Debit Card,Weekly
2041,5073,34,Female,Bag,Electronics,NaN,New York,Not Applicable,Blue,Autumn,3.168539,Yes,Standard,No,NaN,PayPal,Monthly
2047,4628,46,Female,Bag,Accessories,31.37,Phoenix,M,Black,Autumn,3.168539,Yes,Express,No,32.0,Credit Card,Monthly
2061,4106,40,Other,Bag,Accessories,NaN,Phoenix,M,Green,Autumn,2.000000,No,Express,Yes,16.0,PayPal,Weekly
2157,4921,26,Male,Bag,Clothing,1072.05,Los Angeles,M,White,Winter,3.168539,Yes,Standard,No,NaN,PayPal,Monthly
2164,4246,57,Male,Bag,Electronics,NaN,Houston,Not Applicable,Blue,Winter,5.000000,No,Express,Yes,NaN,Debit Card,Quarterly
2194,4334,29,Female,Bag,Clothing,837.03,Houston,M,Black,Winter,3.168539,No,Standard,Yes,NaN,Debit Card,Weekly
2238,4862,37,Other,Bag,Accessories,NaN,New York,M,Black,Summer,3.000000,Yes,Standard,Yes,NaN,Credit Card,Monthly
2264,4147,56,Other,Bag,Electronics,752.44,Phoenix,Not Applicable,Black,Summer,1.000000,No,Express,Yes,14.0,Cash,Quarterly
2274,4059,27,Male,Bag,Electronics,NaN,Chicago,Not Applicable,White,Autumn,3.168539,Yes,Standard,Yes,36.0,PayPal,Quarterly
2283,4651,47,Male,Bag,Clothing,NaN,New York,XL,Blue,Winter,3.000000,No,Standard,Yes,NaN,Cash,Quarterly
2302,5045,60,Male,Bag,Clothing,476.36,Houston,M,Black,Spring,4.000000,No,Standard,No,2.0,Cash,Monthly
2318,4345,43,Male,Bag,Clothing,95.29,New York,M,Blue,Summer,3.168539,Yes,Standard,Yes,50.0,Credit Card,Monthly
2334,4212,45,Other,Bag,Accessories,NaN,Chicago,L,Black,Winter,3.168539,Yes,Standard,No,30.0,PayPal,Weekly
2337,4327,68,Other,Bag,Accessories,NaN,Phoenix,L,Green,Autumn,5.000000,No,Express,Yes,NaN,PayPal,Quarterly
2344,4175,46,Other,Bag,Accessories,1233.29,Houston,S,Blue,Spring,3.168539,No,Express,Yes,8.0,Credit Card,Monthly
2352,4819,41,Male,Bag,Electronics,NaN,Chicago,Not Applicable,Red,Autumn,4.000000,No,Express,Yes,NaN,Debit Card,Monthly
2356,4816,70,Other,Bag,Accessories,NaN,Los Angeles,S,Black,Winter,3.000000,Yes,Standard,No,10.0,Credit Card,Quarterly
2361,4159,59,Male,Bag,Clothing,NaN,Los Angeles,XL,White,Autumn,3.168539,Yes,Standard,No,NaN,Cash,Monthly
2434,4818,23,Male,Bag,Electronics,NaN,Chicago,Not Applicable,White,Spring,1.000000,Yes,Express,No,NaN,Debit Card,Weekly
2441,4325,56,Male,Bag,Accessories,1396.89,New York,M,White,Summer,3.168539,Yes,Express,Yes,NaN,Credit Card,Weekly
2453,4673,19,Other,Bag,Electronics,NaN,Houston,Not Applicable,White,Winter,3.168539,Yes,Express,No,38.0,Cash,Quarterly
2469,4769,28,Male,Bag,Accessories,NaN,Houston,L,Black,Summer,3.168539,No,Express,No,NaN,Cash,Quarterly
2497,5086,22,Male,Bag,Accessories,1156.06,New York,L,Blue,Winter,3.000000,No,Standard,No,18.0,Cash,Weekly
2522,4758,45,Female,Bag,Clothing,NaN,Houston,M,Green,Summer,3.000000,No,Standard,No,NaN,Cash,Weekly
2535,4362,64,Male,Bag,Electronics,NaN,Chicago,Not Applicable,Red,Winter,1.000000,Yes,Express,Yes,NaN,Cash,Quarterly
2564,4963,27,Female,Bag,Clothing,NaN,Phoenix,M,Red,Autumn,3.168539,No,Standard,Yes,NaN,Credit Card,Quarterly
2639,4550,65,Male,Bag,Clothing,NaN,Chicago,L,Blue,Winter,5.000000,No,Standard,No,17.0,Credit Card,Quarterly
2648,4439,55,Other,Bag,Electronics,294.04,New York,Not Applicable,Red,Autumn,3.168539,Yes,Express,No,NaN,PayPal,Weekly
2710,4860,69,Other,Bag,Accessories,NaN,Phoenix,L,Green,Summer,5.000000,No,Standard,No,23.0,Cash,Monthly
2714,4277,38,Female,Bag,Clothing,NaN,Phoenix,XL,Red,Spring,3.168539,No,Standard,No,NaN,Credit Card,Weekly
2731,4099,66,Other,Bag,Clothing,843.15,Los Angeles,S,Black,Spring,5.000000,No,Standard,Yes,8.0,PayPal,Weekly
2735,4624,23,Other,Bag,Clothing,1204.42,Houston,L,Green,Autumn,5.000000,No,Express,No,26.0,Credit Card,Weekly
2750,4655,43,Male,Bag,Clothing,NaN,Phoenix,L,Red,Spring,3.168539,Yes,Standard,No,NaN,Debit Card,Weekly
2799,4990,32,Female,Bag,Accessories,76.80,Phoenix,S,Blue,Autumn,5.000000,No,Express,No,44.0,Debit Card,Monthly
2855,4573,23,Male,Bag,Accessories,1441.51,Phoenix,L,Black,Winter,3.168539,No,Express,Yes,3.0,Credit Card,Quarterly
2860,4407,33,Male,Bag,Accessories,NaN,New York,L,White,Autumn,3.168539,Yes,Standard,Yes,NaN,Credit Card,Monthly
2861,4839,43,Male,Bag,Electronics,1063.29,Houston,Not Applicable,White,Autumn,3.000000,Yes,Standard,Yes,30.0,PayPal,Quarterly
2885,5076,53,Male,Bag,Clothing,12.41,Los Angeles,M,White,Summer,5.000000,No,Standard,Yes,50.0,Credit Card,Monthly
2915,4403,70,Other,Bag,Clothing,583.34,New York,L,Green,Winter,3.168539,Yes,Express,No,20.0,PayPal,Weekly
2936,4521,31,Other,Bag,Electronics,NaN,Houston,Not Applicable,Black,Spring,5.000000,No,Express,No,7.0,PayPal,Weekly
2963,4265,63,Other,Bag,Accessories,708.58,Houston,S,Green,Spring,2.000000,Yes,Standard,Yes,NaN,Debit Card,Monthly
2979,4216,56,Female,Bag,Accessories,713.42,Los Angeles,M,Red,Summer,3.168539,Yes,Standard,No,8.0,PayPal,Monthly
3034,4986,42,Male,Bag,Clothing,561.64,New York,S,Black,Winter,2.000000,No,Express,Yes,NaN,PayPal,Monthly
3044,4771,51,Female,Bag,Electronics,124.66,New York,Not Applicable,White,Autumn,3.168539,No,Express,No,3.0,Cash,Weekly
3047,4978,62,Other,Bag,Accessories,NaN,Phoenix,M,White,Spring,4.000000,Yes,Standard,No,NaN,Cash,Weekly
3060,4286,54,Other,Bag,Clothing,NaN,Houston,M,White,Spring,5.000000,No,Express,Yes,NaN,PayPal,Monthly
3095,4640,62,Male,Bag,Accessories,NaN,New York,M,Black,Summer,3.168539,No,Express,Yes,9.0,Debit Card,Monthly
3136,4331,66,Female,Bag,Accessories,NaN,Phoenix,L,Black,Autumn,3.000000,Yes,Express,No,NaN,Cash,Weekly
3262,4973,61,Female,Bag,Clothing,NaN,Phoenix,S,Black,Summer,4.000000,No,Express,No,42.0,PayPal,Weekly
3281,4230,61,Other,Bag,Electronics,123.39,New York,Not Applicable,Blue,Spring,2.000000,No,Express,Yes,5.0,Debit Card,Weekly
3300,4454,65,Female,Bag,Clothing,NaN,Phoenix,XL,Blue,Winter,3.168539,Yes,Standard,Yes,17.0,Cash,Weekly
3339,5063,31,Male,Bag,Electronics,NaN,Houston,Not Applicable,Blue,Winter,3.168539,Yes,Standard,Yes,1.0,Debit Card,Monthly
3372,4514,61,Female,Bag,Electronics,1161.52,Houston,Not Applicable,Red,Autumn,3.168539,No,Express,Yes,NaN,Cash,Monthly
3433,4909,59,Female,Bag,Electronics,NaN,New York,Not Applicable,Red,Spring,2.000000,Yes,Standard,Yes,40.0,Cash,Monthly
3466,4953,30,Male,Bag,Clothing,207.05,Phoenix,XL,White,Spring,3.000000,No,Standard,No,NaN,Credit Card,Monthly
3530,4243,18,Male,Bag,Clothing,NaN,Los Angeles,XL,Red,Winter,3.168539,No,Express,No,NaN,Cash,Quarterly
3571,4459,64,Female,Bag,Clothing,1010.82,Los Angeles,M,Green,Summer,1.000000,No,Express,No,NaN,Debit Card,Monthly
3578,4222,53,Other,Bag,Electronics,NaN,Los Angeles,Not Applicable,Green,Summer,3.168539,Yes,Express,Yes,19.0,Cash,Weekly
3594,4309,24,Female,Bag,Accessories,NaN,Chicago,S,Red,Winter,3.168539,No,Express,Yes,NaN,Cash,Monthly
3607,4919,25,Other,Bag,Clothing,143.21,Los Angeles,S,Black,Summer,3.168539,No,Express,No,NaN,Credit Card,Monthly
3621,4103,63,Female,Bag,Electronics,1264.71,Chicago,Not Applicable,Green,Summer,3.168539,Yes,Standard,Yes,NaN,Credit Card,Quarterly
3654,5044,65,Female,Bag,Accessories,NaN,Los Angeles,L,Black,Autumn,4.000000,Yes,Express,No,42.0,Debit Card,Weekly
3663,4412,41,Male,Bag,Clothing,1214.49,New York,M,Blue,Spring,2.000000,No,Standard,Yes,1.0,PayPal,Quarterly
3782,4251,20,Male,Bag,Clothing,956.02,Chicago,XL,White,Spring,3.168539,Yes,Standard,Yes,6.0,Cash,Monthly
3786,5001,24,Other,Bag,Accessories,NaN,Chicago,L,Green,Autumn,3.000000,Yes,Standard,No,45.0,Cash,Weekly
3863,4060,25,Female,Bag,Electronics,NaN,Houston,Not Applicable,White,Autumn,3.168539,No,Standard,No,NaN,Credit Card,Quarterly
3882,4380,61,Other,Bag,Electronics,1487.00,Chicago,Not Applicable,Red,Spring,2.000000,No,Standard,No,9.0,Debit Card,Quarterly
3921,4791,30,Other,Bag,Electronics,NaN,Houston,Not Applicable,White,Autumn,3.168539,Yes,Standard,Yes,NaN,Credit Card,Monthly
3924,4229,68,Other,Bag,Electronics,882.19,New York,Not Applicable,Green,Winter,3.168539,No,Standard,Yes,NaN,Debit Card,Weekly
3953,4335,22,Other,Bag,Accessories,NaN,Los Angeles,M,Blue,Spring,5.000000,No,Standard,No,1.0,Debit Card,Weekly
4009,4613,36,Male,Bag,Accessories,1186.54,Los Angeles,S,Blue,Summer,3.168539,No,Standard,No,39.0,Debit Card,Quarterly
4078,4902,29,Other,Bag,Clothing,398.16,New York,XL,Red,Spring,3.168539,Yes,Standard,Yes,NaN,Credit Card,Quarterly
4084,4786,47,Female,Bag,Electronics,532.19,Los Angeles,Not Applicable,White,Spring,5.000000,No,Standard,Yes,NaN,Debit Card,Quarterly
4090,4787,23,Other,Bag,Clothing,1380.02,Houston,M,Green,Spring,3.168539,Yes,Standard,No,NaN,PayPal,Quarterly
4096,4226,41,Female,Bag,Clothing,1472.22,Chicago,L,Green,Spring,3.168539,No,Express,Yes,NaN,Debit Card,Monthly
4145,4301,59,Male,Bag,Accessories,862.98,Phoenix,S,Blue,Autumn,3.168539,No,Standard,Yes,12.0,Cash,Monthly
4150,4279,42,Other,Bag,Clothing,NaN,Houston,XL,Red,Spring,1.000000,No,Express,No,5.0,Credit Card,Weekly
4173,4091,44,Other,Bag,Clothing,517.70,Houston,S,Red,Spring,3.168539,Yes,Standard,No,NaN,Credit Card,Quarterly
4226,4386,39,Other,Bag,Accessories,NaN,Phoenix,S,Black,Spring,3.168539,No,Express,No,21.0,Credit Card,Quarterly
4276,5059,62,Other,Bag,Electronics,142.24,Phoenix,Not Applicable,Blue,Autumn,3.168539,Yes,Standard,Yes,28.0,Debit Card,Quarterly
4298,4874,43,Female,Bag,Clothing,615.29,New York,XL,Red,Autumn,3.000000,Yes,Express,No,NaN,Debit Card,Quarterly
4315,4030,41,Male,Bag,Accessories,NaN,Phoenix,L,Blue,Winter,3.000000,Yes,Express,Yes,34.0,Cash,Quarterly
4319,4855,60,Male,Bag,Accessories,1318.84,Phoenix,L,Blue,Winter,3.168539,Yes,Standard,No,NaN,PayPal,Weekly
4405,4617,45,Male,Bag,Clothing,NaN,Los Angeles,XL,Red,Summer,3.168539,Yes,Standard,No,18.0,Debit Card,Monthly
4406,4092,55,Other,Bag,Accessories,NaN,Phoenix,S,Red,Autumn,4.000000,No,Express,Yes,33.0,Debit Card,Monthly
4419,4689,69,Male,Bag,Clothing,982.87,Houston,XL,Red,Spring,4.000000,No,Standard,No,24.0,PayPal,Monthly
4422,4504,29,Male,Bag,Electronics,NaN,Los Angeles,Not Applicable,Black,Summer,2.000000,No,Standard,Yes,NaN,PayPal,Monthly
4490,4087,22,Female,Bag,Accessories,NaN,New York,M,Green,Summer,2.000000,No,Standard,No,12.0,Credit Card,Weekly
4565,4300,40,Female,Bag,Clothing,1400.99,Chicago,S,White,Spring,3.168539,No,Express,Yes,NaN,Debit Card,Monthly
4566,4199,44,Other,Bag,Accessories,NaN,Houston,M,Black,Autumn,3.168539,Yes,Standard,Yes,25.0,Cash,Monthly
4574,4478,42,Female,Bag,Accessories,1216.92,Houston,L,Green,Spring,3.000000,No,Standard,Yes,NaN,Cash,Weekly
4590,5022,68,Female,Bag,Accessories,1103.92,Los Angeles,L,Black,Winter,1.000000,Yes,Standard,No,NaN,Cash,Quarterly
4592,4719,54,Female,Bag,Electronics,1144.77,New York,Not Applicable,Green,Summer,3.168539,Yes,Express,No,9.0,Credit Card,Weekly
4657,4676,55,Other,Bag,Accessories,544.69,Phoenix,S,Black,Autumn,2.000000,Yes,Standard,Yes,NaN,Cash,Monthly
4672,4975,61,Male,Bag,Accessories,NaN,Houston,L,Red,Spring,5.000000,No,Standard,Yes,3.0,PayPal,Weekly
4769,4101,22,Male,Bag,Clothing,125.59,Houston,XL,Blue,Spring,3.168539,Yes,Standard,Yes,NaN,Cash,Weekly
4782,4638,33,Other,Bag,Accessories,597.06,Los Angeles,L,Blue,Summer,4.000000,Yes,Express,No,40.0,Credit Card,Weekly
4809,4927,34,Other,Bag,Clothing,NaN,Phoenix,L,Black,Autumn,3.000000,No,Standard,No,NaN,Debit Card,Quarterly
4868,4110,27,Other,Bag,Electronics,NaN,Los Angeles,Not Applicable,White,Spring,1.000000,No,Standard,No,NaN,Debit Card,Monthly
4872,4233,27,Female,Bag,Accessories,47.79,Houston,L,Red,Winter,3.000000,No,Express,No,NaN,PayPal,Monthly
4984,4658,49,Other,Bag,Clothing,NaN,Chicago,M,Blue,Winter,4.000000,No,Express,No,NaN,PayPal,Monthly
4995,4642,27,Female,Bag,Electronics,799.62,Los Angeles,Not Applicable,Red,Winter,1.000000,Yes,Standard,No,39.0,Credit Card,Monthly
4998,4015,34,Other,Bag,Electronics,409.98,Chicago,Not Applicable,Blue,Summer,3.168539,Yes,Standard,Yes,NaN,PayPal,Monthly
5008,4984,24,Female,Bag,Electronics,NaN,New York,Not Applicable,White,Autumn,3.168539,Yes,Standard,No,1.0,Debit Card,Monthly

In [27]:
df['Review Rating'].mean()

np.float64(3.668195100022477)

In [30]:
#check median of Review Rating
df['Review Rating'].median()

np.float64(3.7)

In [31]:
# check mode of Review Rating
df['Review Rating'].mode()

0    4.0
Name: Review Rating, dtype: float64

In [32]:
df.groupby('Item Purchased')['Review Rating'].mean()

Item Purchased
Backpack      3.758333
Bag           3.168539
Belt          3.762963
Blouse        3.677647
Boots         3.813194
Coat          3.721875
Dress         3.750000
Gloves        3.862774
Handbag       3.771975
Hat           3.796753
Headphones    3.075949
Hoodie        3.716779
Jacket        3.761446
Jeans         3.651969
Jewelry       3.761850
Laptop        3.191176
Pants         3.720833
Phone         2.939024
Sandals       3.837037
Scarf         3.702564
Shirt         3.427273
Shoes         3.546154
Shorts        3.722981
Skirt         3.779747
Sneakers      3.757931
Socks         3.755063
Sunglasses    3.745679
Sweater       3.768712
T-shirt       3.790541
Watch         3.100000
Name: Review Rating, dtype: float64

In [33]:
#FillinG null Values of Review Ratings with the mean of each Item Purchased

df['Review Rating']=df['Review Rating'].fillna(df.groupby('Item Purchased')['Review Rating'].transform('mean'))

In [40]:
df['Review Rating']=df['Review Rating'].round(2)

In [41]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.20,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.90,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.10,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.20,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.60,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.0,California,S,Beige,Summer,3.40,No,2-Day Shipping,No,15.0,PayPal,Annually
6,1135,62,Male,T-shirt,Clothing,81.0,Wisconsin,M,Brown,Summer,3.79,No,Express,Yes,2.0,Venmo,Every 3 Months
7,1411,61,Male,Hat,Accessories,93.0,Tennessee,M,Purple,Summer,4.00,No,Store Pickup,Yes,18.0,Debit Card,Annually
8,113,37,Male,Gloves,Accessories,65.0,Florida,M,Red,Spring,4.30,Yes,Free Shipping,Yes,28.0,PayPal,Bi-Weekly
9,166,42,Male,Handbag,Accessories,60.0,Kentucky,S,Yellow,Winter,2.80,Yes,Store Pickup,Yes,7.0,Cash,Monthly

## Previous Purchase

In [43]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [45]:
df['Previous Purchases']=df['Previous Purchases'].fillna(0)

In [46]:
df.groupby('Item Purchased')['Purchase Amount (USD)'].mean()

Item Purchased
Backpack       60.111111
Bag           735.773625
Belt           59.993902
Blouse         60.802326
Boots          62.616438
Coat           57.851852
Dress          62.168675
Gloves         60.550000
Handbag        57.987261
Hat            60.787097
Headphones    831.344565
Hoodie         58.059603
Jacket         56.777108
Jeans          60.456693
Jewelry        59.011494
Laptop        805.502027
Pants          59.005848
Phone         734.477349
Sandals        57.527607
Scarf          61.157233
Shirt         279.935608
Shoes         276.343790
Shorts         60.073620
Skirt          59.723270
Sneakers       59.551724
Socks          58.188679
Sunglasses     59.975610
Sweater        57.638554
T-shirt        63.093333
Watch         685.231471
Name: Purchase Amount (USD), dtype: float64

In [51]:
# Replace Null Value in Purchase amount(USD) with mean of Purchase Amount by Item Value

df['Purchase Amount (USD)']=df['Purchase Amount (USD)'].fillna(df.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean'))

### CHECKING DUPLICATE

In [57]:
df.duplicated().sum()

np.int64(50)

In [58]:
df[df.duplicated()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.30,No,Free Shipping,No,19.0,Cash,Monthly
1402,1621,25,Male,Hat,Accessories,47.0,Virginia,M,Charcoal,Winter,3.10,No,2-Day Shipping,Yes,27.0,PayPal,Every 3 Months
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.50,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1600,2135,55,Male,Sandals,Footwear,41.0,Virginia,XL,Maroon,Winter,2.90,No,Standard,No,35.0,Credit Card,Fortnightly
1665,1846,51,Male,Sandals,Footwear,78.0,Delaware,M,Orange,Winter,2.80,No,2-Day Shipping,No,39.0,Bank Transfer,Quarterly
1797,3639,40,Female,Backpack,Accessories,20.0,Kansas,M,Olive,Spring,4.60,No,Express,No,50.0,PayPal,Bi-Weekly
1870,3456,49,Female,T-shirt,Clothing,89.0,Ohio,M,Orange,Fall,4.70,No,Standard,No,13.0,Venmo,Annually
2033,1812,42,Male,Belt,Accessories,77.0,Wisconsin,L,Blue,Summer,3.60,No,Standard,No,33.0,Bank Transfer,Annually
2113,3040,59,Female,Blouse,Clothing,48.0,Alabama,L,Blue,Spring,3.20,No,Next Day Air,No,31.0,PayPal,Bi-Weekly
2226,1371,27,Male,Scarf,Accessories,67.0,Montana,L,Peach,Summer,3.70,No,2-Day Shipping,Yes,41.0,Bank Transfer,Every 3 Months
2358,2977,30,Female,Coat,Outerwear,97.0,Nebraska,M,Silver,Summer,2.80,No,Express,No,28.0,Cash,Fortnightly
2447,2678,45,Female,Shorts,Clothing,43.0,Connecticut,L,Olive,Spring,3.80,No,Next Day Air,No,6.0,PayPal,Every 3 Months
2630,992,20,Male,Shorts,Clothing,97.0,Wisconsin,XL,White,Spring,2.70,Yes,Standard,Yes,40.0,Bank Transfer,Bi-Weekly
2642,1566,58,Male,Sunglasses,Accessories,93.0,Idaho,L,Peach,Fall,4.20,No,Free Shipping,Yes,48.0,PayPal,Annually
2739,2227,22,Male,Shirt,Clothing,72.0,Missouri,L,Blue,Spring,4.80,No,Store Pickup,No,28.0,Cash,Annually
2740,3487,51,Female,Shorts,Clothing,89.0,North Carolina,L,Charcoal,Winter,4.90,No,Standard,No,6.0,PayPal,Weekly
2800,2069,70,Male,Jewelry,Accessories,81.0,Vermont,XL,Black,Summer,3.90,No,Store Pickup,No,44.0,Venmo,Monthly
2905,2158,41,Male,Handbag,Accessories,68.0,Mississippi,L,Turquoise,Winter,4.00,No,Next Day Air,No,41.0,Venmo,Fortnightly
2922,3334,55,Female,Jeans,Clothing,35.0,Minnesota,M,Violet,Spring,4.20,No,Express,No,3.0,PayPal,Monthly
3036,258,20,Male,Handbag,Accessories,53.0,West Virginia,M,Red,Summer,4.50,Yes,Express,Yes,5.0,Credit Card,Quarterly
3065,3887,37,Female,Jewelry,Accessories,92.0,Iowa,S,Brown,Summer,3.90,No,Express,No,40.0,Debit Card,Quarterly
3185,1609,26,Male,Sandals,Footwear,58.0,Nebraska,XL,Cyan,Fall,4.60,No,Next Day Air,Yes,12.0,Bank Transfer,Bi-Weekly
3357,3091,29,Female,Shirt,Clothing,36.0,Texas,M,Peach,Summer,4.90,No,Store Pickup,No,15.0,Bank Transfer,Quarterly
3390,603,37,Male,Shoes,Footwear,58.0,Oregon,L,Lavender,Summer,4.20,Yes,Next Day Air,Yes,10.0,Cash,Every 3 Months
3538,1698,36,Male,Shirt,Clothing,87.0,South Carolina,L,Lavender,Fall,3.50,No,Next Day Air,No,48.0,Credit Card,Every 3 Months
3683,1209,20,Male,Boots,Footwear,100.0,Wisconsin,S,Red,Winter,3.81,No,2-Day Shipping,Yes,8.0,Debit Card,Annually
3698,172,29,Male,Shorts,Clothing,35.0,Virginia,M,Blue,Summer,3.60,Yes,Store Pickup,Yes,4.0,Credit Card,Weekly
3742,323,41,Male,Belt,Accessories,95.0,Tennessee,S,Cyan,Winter,3.00,Yes,Standard,Yes,47.0,Credit Card,Monthly
3810,2429,65,Male,T-shirt,Clothing,38.0,Idaho,M,Violet,Spring,4.40,No,Next Day Air,No,34.0,Debit Card,Annually
3843,615,68,Male,Jewelry,Accessories,85.0,Idaho,M,Lavender,Winter,4.00,Yes,Standard,Yes,21.0,Credit Card,Bi-Weekly
3961,2558,70,Male,Shorts,Clothing,23.0,Oklahoma,L,Cyan,Spring,3.90,No,Standard,No,17.0,PayPal,Fortnightly
3987,3507,18,Female,Shirt,Clothing,57.0,Illinois,L,Olive,Winter,3.70,No,2-Day Shipping,No,12.0,Cash,Fortnightly
4050,3287,45,Female,Jacket,Outerwear,67.0,Illinois,L,Pink,Winter,5.00,No,Express,No,4.0,Venmo,Fortnightly
4059,227,29,Male,Shoes,Footwear,74.0,Texas,L,Violet,Spring,3.30,Yes,Free Shipping,Yes,5.0,PayPal,Monthly
4131,2642,25,Male,Sunglasses,Accessories,60.0,Vermont,XL,Olive,Winter,2.70,No,Next Day Air,No,20.0,Bank Transfer,Every 3 Months
4183,1523,38,Male,Shorts,Clothing,72.0,Tennessee,L,Yellow,Spring,4.80,No,Free Shipping,Yes,5.0,Debit Card,Monthly
4330,3716,63,Female,Sunglasses,Accessories,34.0,Nebraska,S,Orange,Fall,3.40,No,Free Shipping,No,2.0,Bank Transfer,Monthly
4390,3846,58,Female,Sweater,Clothing,52.0,California,M,Green,Winter,4.90,No,Standard,No,46.0,Venmo,Annually
4445,3644,53,Female,Scarf,Accessories,96.0,Tennessee,XL,Magenta,Fall,3.20,No,Standard,No,47.0,Debit Card,Annually
4468,473,20,Male,Jeans,Clothing,39.0,Georgia,L,Gray,Winter,3.90,Yes,Free Shipping,Yes,3.0,Bank Transfer,Quarterly
4513,1317,28,Male,Belt,Accessories,32.0,Arkansas,S,Lavender,Spring,4.60,No,Standard,Yes,14.0,Debit Card,Bi-Weekly
4558,3339,29,Female,Skirt,Clothing,94.0,Minnesota,L,White,Winter,2.90,No,2-Day Shipping,No,46.0,Credit Card,Monthly
4595,3577,29,Female,Boots,Footwear,24.0,Maine,L,Yellow,Spring,3.00,No,Express,No,12.0,Venmo,Bi-Weekly
4664,2689,53,Female,Handbag,Accessories,63.0,West Virginia,XL,Turquoise,Spring,2.90,No,2-Day Shipping,No,18.0,Credit Card,Every 3 Months
4717,2800,23,Female,T-shirt,Clothing,89.0,Maine,L,Pink,Spring,3.90,No,Free Shipping,No,9.0,Bank Transfer,Every 3 Months
4735,2182,22,Male,Handbag,Accessories,63.0,Hawaii,M,Black,Fall,3.20,No,Free Shipping,No,32.0,Bank Transfer,Bi-Weekly
4841,2622,48,Male,Shoes,Footwear,46.0,Maine,M,Beige,Winter,3.00,No,Express,No,21.0,Bank Transfer,Annually
4887,3875,70,Female,Sweater,Clothing,54.0,Nevada,XL,Beige,Summer,3.90,No,2-Day Shipping,No,33.0,Credit Card,Bi-Weekly
4901,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.50,No,Standard,Yes,25.0,Debit Card,Monthly
5037,3439,26,Female,Shirt,Clothing,71.0,Kentucky,M,Violet,Fall,3.00,No,Store Pickup,No,33.0,Credit Card,Monthly

In [59]:
# to cross check
df[df['Customer ID']==974]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
483,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.5,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.5,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly

In [66]:
df.duplicated().sum()

np.int64(0)

In [65]:
# deleting duplicate value
df=df.drop_duplicates(subset=['Customer ID'],keep='first')

In [109]:
df.count()

customer_id               5000
age                       5000
gender                    5000
item_purchased            5000
category                  5000
purchase_amount           5000
location                  5000
size                      5000
color                     5000
season                    5000
review_rating             5000
subscription_status       5000
shipping_type             5000
discount_applied          5000
previous_purchases        5000
payment_method            5000
frequency_of_purchases    5000
dtype: int64

In [68]:
# Renaming Column name To work properly in sql server or mysql
df.columns=df.columns.str.replace(" ","_")

In [73]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount_(USD)', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Previous_Purchases', 'Payment_Method',
       'Frequency_of_Purchases'],
      dtype='str')

In [74]:
# conveting columns into lower case
df.columns=df.columns.str.lower()

In [78]:
# renaming 'purchase_amount_(usd)' into 'purchase_amount'
df=df.rename(columns={"purchase_amount_(usd)":"purchase_amount"})

In [79]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='str')

#### connecting to sql server

In [93]:
import sqlalchemy
import pyodbc
server = r"KARAN\SQLEXPRESS"   # your SQL Server instance name
database = "data_analysis_project"  # replace with your DB name
driver = "ODBC Driver 17 for SQL Server"

# Connection string using Windows Authentication
connection_string = f"mssql+pyodbc://@{server}/{database}?driver={driver}"

# Create engine
engine = sqlalchemy.create_engine(connection_string)
print("done")

done

In [110]:
table_name="customer_behaviour_analysis"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print("Successfully loaded into table")

Successfully loaded into table